{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='httpProxy', url='', help='"HTTPProxy is an Ingress CRD specification."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of HTTPProxy', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'projectcontour.io/v1',
    kind: 'HTTPProxy',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"HTTPProxySpec defines the spec of the CRD."'),
  spec: {
    '#includes':: d.obj(help='"Includes allow for specific routing configuration to be included from another HTTPProxy, possibly in another namespace."'),
    includes: {
      '#conditions':: d.obj(help='"Conditions are a set of rules that are applied to included HTTPProxies. In effect, they are added onto the Conditions of included HTTPProxy Route structs. When applied, they are merged using AND, with one exception: There can be only one Prefix MatchCondition per Conditions slice. More than one Prefix, or contradictory Conditions, will make the include invalid."'),
      conditions: {
        '#header':: d.obj(help='"Header specifies the header condition to match."'),
        header: {
          '#withContains':: d.fn(help='"Contains specifies a substring that must be present in the header value."', args=[d.arg(name='contains', type=d.T.string)]),
          withContains(contains): { header+: { contains: contains } },
          '#withExact':: d.fn(help='"Exact specifies a string that the header value must be equal to."', args=[d.arg(name='exact', type=d.T.string)]),
          withExact(exact): { header+: { exact: exact } },
          '#withName':: d.fn(help='"Name is the name of the header to match against. Name is required. Header names are case insensitive."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { header+: { name: name } },
          '#withNotcontains':: d.fn(help='"NotContains specifies a substring that must not be present in the header value."', args=[d.arg(name='notcontains', type=d.T.string)]),
          withNotcontains(notcontains): { header+: { notcontains: notcontains } },
          '#withNotexact':: d.fn(help='"NoExact specifies a string that the header value must not be equal to. The condition is true if the header has any other value."', args=[d.arg(name='notexact', type=d.T.string)]),
          withNotexact(notexact): { header+: { notexact: notexact } },
          '#withPresent':: d.fn(help='"Present specifies that condition is true when the named header is present, regardless of its value. Note that setting Present to false does not make the condition true if the named header is absent."', args=[d.arg(name='present', type=d.T.boolean)]),
          withPresent(present): { header+: { present: present } },
        },
        '#withPrefix':: d.fn(help='"Prefix defines a prefix match for a request."', args=[d.arg(name='prefix', type=d.T.string)]),
        withPrefix(prefix): { prefix: prefix },
      },
      '#withConditions':: d.fn(help='"Conditions are a set of rules that are applied to included HTTPProxies. In effect, they are added onto the Conditions of included HTTPProxy Route structs. When applied, they are merged using AND, with one exception: There can be only one Prefix MatchCondition per Conditions slice. More than one Prefix, or contradictory Conditions, will make the include invalid."', args=[d.arg(name='conditions', type=d.T.array)]),
      withConditions(conditions): { conditions: if std.isArray(v=conditions) then conditions else [conditions] },
      '#withConditionsMixin':: d.fn(help='"Conditions are a set of rules that are applied to included HTTPProxies. In effect, they are added onto the Conditions of included HTTPProxy Route structs. When applied, they are merged using AND, with one exception: There can be only one Prefix MatchCondition per Conditions slice. More than one Prefix, or contradictory Conditions, will make the include invalid."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='conditions', type=d.T.array)]),
      withConditionsMixin(conditions): { conditions+: if std.isArray(v=conditions) then conditions else [conditions] },
      '#withName':: d.fn(help='"Name of the HTTPProxy"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withNamespace':: d.fn(help='"Namespace of the HTTPProxy to include. Defaults to the current namespace if not supplied."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { namespace: namespace },
    },
    '#routes':: d.obj(help='"Routes are the ingress routes. If TCPProxy is present, Routes is ignored."'),
    routes: {
      '#authPolicy':: d.obj(help='"AuthPolicy updates the authorization policy that was set on the root HTTPProxy object for client requests that match this route."'),
      authPolicy: {
        '#withContext':: d.fn(help='"Context is a set of key/value pairs that are sent to the authentication server in the check request. If a context is provided at an enclosing scope, the entries are merged such that the inner scope overrides matching keys from the outer scope."', args=[d.arg(name='context', type=d.T.object)]),
        withContext(context): { authPolicy+: { context: context } },
        '#withContextMixin':: d.fn(help='"Context is a set of key/value pairs that are sent to the authentication server in the check request. If a context is provided at an enclosing scope, the entries are merged such that the inner scope overrides matching keys from the outer scope."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='context', type=d.T.object)]),
        withContextMixin(context): { authPolicy+: { context+: context } },
        '#withDisabled':: d.fn(help='"When true, this field disables client request authentication for the scope of the policy."', args=[d.arg(name='disabled', type=d.T.boolean)]),
        withDisabled(disabled): { authPolicy+: { disabled: disabled } },
      },
      '#conditions':: d.obj(help='"Conditions are a set of rules that are applied to a Route. When applied, they are merged using AND, with one exception: There can be only one Prefix MatchCondition per Conditions slice. More than one Prefix, or contradictory Conditions, will make the route invalid."'),
      conditions: {
        '#header':: d.obj(help='"Header specifies the header condition to match."'),
        header: {
          '#withContains':: d.fn(help='"Contains specifies a substring that must be present in the header value."', args=[d.arg(name='contains', type=d.T.string)]),
          withContains(contains): { header+: { contains: contains } },
          '#withExact':: d.fn(help='"Exact specifies a string that the header value must be equal to."', args=[d.arg(name='exact', type=d.T.string)]),
          withExact(exact): { header+: { exact: exact } },
          '#withName':: d.fn(help='"Name is the name of the header to match against. Name is required. Header names are case insensitive."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { header+: { name: name } },
          '#withNotcontains':: d.fn(help='"NotContains specifies a substring that must not be present in the header value."', args=[d.arg(name='notcontains', type=d.T.string)]),
          withNotcontains(notcontains): { header+: { notcontains: notcontains } },
          '#withNotexact':: d.fn(help='"NoExact specifies a string that the header value must not be equal to. The condition is true if the header has any other value."', args=[d.arg(name='notexact', type=d.T.string)]),
          withNotexact(notexact): { header+: { notexact: notexact } },
          '#withPresent':: d.fn(help='"Present specifies that condition is true when the named header is present, regardless of its value. Note that setting Present to false does not make the condition true if the named header is absent."', args=[d.arg(name='present', type=d.T.boolean)]),
          withPresent(present): { header+: { present: present } },
        },
        '#withPrefix':: d.fn(help='"Prefix defines a prefix match for a request."', args=[d.arg(name='prefix', type=d.T.string)]),
        withPrefix(prefix): { prefix: prefix },
      },
      '#healthCheckPolicy':: d.obj(help='"The health check policy for this route."'),
      healthCheckPolicy: {
        '#withHealthyThresholdCount':: d.fn(help='"The number of healthy health checks required before a host is marked healthy"', args=[d.arg(name='healthyThresholdCount', type=d.T.integer)]),
        withHealthyThresholdCount(healthyThresholdCount): { healthCheckPolicy+: { healthyThresholdCount: healthyThresholdCount } },
        '#withHost':: d.fn(help='"The value of the host header in the HTTP health check request. If left empty (default value), the name \\"contour-envoy-healthcheck\\" will be used."', args=[d.arg(name='host', type=d.T.string)]),
        withHost(host): { healthCheckPolicy+: { host: host } },
        '#withIntervalSeconds':: d.fn(help='"The interval (seconds) between health checks"', args=[d.arg(name='intervalSeconds', type=d.T.integer)]),
        withIntervalSeconds(intervalSeconds): { healthCheckPolicy+: { intervalSeconds: intervalSeconds } },
        '#withPath':: d.fn(help='"HTTP endpoint used to perform health checks on upstream service"', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { healthCheckPolicy+: { path: path } },
        '#withTimeoutSeconds':: d.fn(help='"The time to wait (seconds) for a health check response"', args=[d.arg(name='timeoutSeconds', type=d.T.integer)]),
        withTimeoutSeconds(timeoutSeconds): { healthCheckPolicy+: { timeoutSeconds: timeoutSeconds } },
        '#withUnhealthyThresholdCount':: d.fn(help='"The number of unhealthy health checks required before a host is marked unhealthy"', args=[d.arg(name='unhealthyThresholdCount', type=d.T.integer)]),
        withUnhealthyThresholdCount(unhealthyThresholdCount): { healthCheckPolicy+: { unhealthyThresholdCount: unhealthyThresholdCount } },
      },
      '#loadBalancerPolicy':: d.obj(help='"The load balancing policy for this route."'),
      loadBalancerPolicy: {
        '#withStrategy':: d.fn(help='"Strategy specifies the policy used to balance requests across the pool of backend pods. Valid policy names are `Random`, `RoundRobin`, `WeightedLeastRequest`, `Random` and `Cookie`. If an unknown strategy name is specified or no policy is supplied, the default `RoundRobin` policy is used."', args=[d.arg(name='strategy', type=d.T.string)]),
        withStrategy(strategy): { loadBalancerPolicy+: { strategy: strategy } },
      },
      '#pathRewritePolicy':: d.obj(help='"The policy for rewriting the path of the request URL after the request has been routed to a Service."'),
      pathRewritePolicy: {
        '#replacePrefix':: d.obj(help='"ReplacePrefix describes how the path prefix should be replaced."'),
        replacePrefix: {
          '#withPrefix':: d.fn(help='"Prefix specifies the URL path prefix to be replaced. \\n If Prefix is specified, it must exactly match the MatchCondition prefix that is rendered by the chain of including HTTPProxies and only that path prefix will be replaced by Replacement. This allows HTTPProxies that are included through multiple roots to only replace specific path prefixes, leaving others unmodified. \\n If Prefix is not specified, all routing prefixes rendered by the include chain will be replaced."', args=[d.arg(name='prefix', type=d.T.string)]),
          withPrefix(prefix): { prefix: prefix },
          '#withReplacement':: d.fn(help='"Replacement is the string that the routing path prefix will be replaced with. This must not be empty."', args=[d.arg(name='replacement', type=d.T.string)]),
          withReplacement(replacement): { replacement: replacement },
        },
        '#withReplacePrefix':: d.fn(help='"ReplacePrefix describes how the path prefix should be replaced."', args=[d.arg(name='replacePrefix', type=d.T.array)]),
        withReplacePrefix(replacePrefix): { pathRewritePolicy+: { replacePrefix: if std.isArray(v=replacePrefix) then replacePrefix else [replacePrefix] } },
        '#withReplacePrefixMixin':: d.fn(help='"ReplacePrefix describes how the path prefix should be replaced."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='replacePrefix', type=d.T.array)]),
        withReplacePrefixMixin(replacePrefix): { pathRewritePolicy+: { replacePrefix+: if std.isArray(v=replacePrefix) then replacePrefix else [replacePrefix] } },
      },
      '#requestHeadersPolicy':: d.obj(help='"The policy for managing request headers during proxying."'),
      requestHeadersPolicy: {
        '#set':: d.obj(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."'),
        set: {
          '#withName':: d.fn(help='"Name represents a key of a header"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withValue':: d.fn(help='"Value represents the value of a header specified by a key"', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#withRemove':: d.fn(help='"Remove specifies a list of HTTP header names to remove."', args=[d.arg(name='remove', type=d.T.array)]),
        withRemove(remove): { requestHeadersPolicy+: { remove: if std.isArray(v=remove) then remove else [remove] } },
        '#withRemoveMixin':: d.fn(help='"Remove specifies a list of HTTP header names to remove."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remove', type=d.T.array)]),
        withRemoveMixin(remove): { requestHeadersPolicy+: { remove+: if std.isArray(v=remove) then remove else [remove] } },
        '#withSet':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."', args=[d.arg(name='set', type=d.T.array)]),
        withSet(set): { requestHeadersPolicy+: { set: if std.isArray(v=set) then set else [set] } },
        '#withSetMixin':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='set', type=d.T.array)]),
        withSetMixin(set): { requestHeadersPolicy+: { set+: if std.isArray(v=set) then set else [set] } },
      },
      '#responseHeadersPolicy':: d.obj(help="\"The policy for managing response headers during proxying. Rewriting the 'Host' header is not supported.\""),
      responseHeadersPolicy: {
        '#set':: d.obj(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."'),
        set: {
          '#withName':: d.fn(help='"Name represents a key of a header"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withValue':: d.fn(help='"Value represents the value of a header specified by a key"', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#withRemove':: d.fn(help='"Remove specifies a list of HTTP header names to remove."', args=[d.arg(name='remove', type=d.T.array)]),
        withRemove(remove): { responseHeadersPolicy+: { remove: if std.isArray(v=remove) then remove else [remove] } },
        '#withRemoveMixin':: d.fn(help='"Remove specifies a list of HTTP header names to remove."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remove', type=d.T.array)]),
        withRemoveMixin(remove): { responseHeadersPolicy+: { remove+: if std.isArray(v=remove) then remove else [remove] } },
        '#withSet':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."', args=[d.arg(name='set', type=d.T.array)]),
        withSet(set): { responseHeadersPolicy+: { set: if std.isArray(v=set) then set else [set] } },
        '#withSetMixin':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='set', type=d.T.array)]),
        withSetMixin(set): { responseHeadersPolicy+: { set+: if std.isArray(v=set) then set else [set] } },
      },
      '#retryPolicy':: d.obj(help='"The retry policy for this route."'),
      retryPolicy: {
        '#withCount':: d.fn(help='"NumRetries is maximum allowed number of retries. If not supplied, the number of retries is one."', args=[d.arg(name='count', type=d.T.integer)]),
        withCount(count): { retryPolicy+: { count: count } },
        '#withPerTryTimeout':: d.fn(help='"PerTryTimeout specifies the timeout per retry attempt. Ignored if NumRetries is not supplied."', args=[d.arg(name='perTryTimeout', type=d.T.string)]),
        withPerTryTimeout(perTryTimeout): { retryPolicy+: { perTryTimeout: perTryTimeout } },
        '#withRetriableStatusCodes':: d.fn(help='"RetriableStatusCodes specifies the HTTP status codes that should be retried. \\n This field is only respected when you include `retriable-status-codes` in the `RetryOn` field."', args=[d.arg(name='retriableStatusCodes', type=d.T.array)]),
        withRetriableStatusCodes(retriableStatusCodes): { retryPolicy+: { retriableStatusCodes: if std.isArray(v=retriableStatusCodes) then retriableStatusCodes else [retriableStatusCodes] } },
        '#withRetriableStatusCodesMixin':: d.fn(help='"RetriableStatusCodes specifies the HTTP status codes that should be retried. \\n This field is only respected when you include `retriable-status-codes` in the `RetryOn` field."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='retriableStatusCodes', type=d.T.array)]),
        withRetriableStatusCodesMixin(retriableStatusCodes): { retryPolicy+: { retriableStatusCodes+: if std.isArray(v=retriableStatusCodes) then retriableStatusCodes else [retriableStatusCodes] } },
        '#withRetryOn':: d.fn(help='"RetryOn specifies the conditions on which to retry a request. \\n Supported [HTTP conditions](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on): \\n - `5xx` - `gateway-error` - `reset` - `connect-failure` - `retriable-4xx` - `refused-stream` - `retriable-status-codes` - `retriable-headers` \\n Supported [gRPC conditions](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-grpc-on): \\n - `cancelled` - `deadline-exceeded` - `internal` - `resource-exhausted` - `unavailable`"', args=[d.arg(name='retryOn', type=d.T.array)]),
        withRetryOn(retryOn): { retryPolicy+: { retryOn: if std.isArray(v=retryOn) then retryOn else [retryOn] } },
        '#withRetryOnMixin':: d.fn(help='"RetryOn specifies the conditions on which to retry a request. \\n Supported [HTTP conditions](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on): \\n - `5xx` - `gateway-error` - `reset` - `connect-failure` - `retriable-4xx` - `refused-stream` - `retriable-status-codes` - `retriable-headers` \\n Supported [gRPC conditions](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-grpc-on): \\n - `cancelled` - `deadline-exceeded` - `internal` - `resource-exhausted` - `unavailable`"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='retryOn', type=d.T.array)]),
        withRetryOnMixin(retryOn): { retryPolicy+: { retryOn+: if std.isArray(v=retryOn) then retryOn else [retryOn] } },
      },
      '#services':: d.obj(help='"Services are the services to proxy traffic."'),
      services: {
        '#requestHeadersPolicy':: d.obj(help="\"The policy for managing request headers during proxying. Rewriting the 'Host' header is not supported.\""),
        requestHeadersPolicy: {
          '#set':: d.obj(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."'),
          set: {
            '#withName':: d.fn(help='"Name represents a key of a header"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withValue':: d.fn(help='"Value represents the value of a header specified by a key"', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#withRemove':: d.fn(help='"Remove specifies a list of HTTP header names to remove."', args=[d.arg(name='remove', type=d.T.array)]),
          withRemove(remove): { requestHeadersPolicy+: { remove: if std.isArray(v=remove) then remove else [remove] } },
          '#withRemoveMixin':: d.fn(help='"Remove specifies a list of HTTP header names to remove."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remove', type=d.T.array)]),
          withRemoveMixin(remove): { requestHeadersPolicy+: { remove+: if std.isArray(v=remove) then remove else [remove] } },
          '#withSet':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."', args=[d.arg(name='set', type=d.T.array)]),
          withSet(set): { requestHeadersPolicy+: { set: if std.isArray(v=set) then set else [set] } },
          '#withSetMixin':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='set', type=d.T.array)]),
          withSetMixin(set): { requestHeadersPolicy+: { set+: if std.isArray(v=set) then set else [set] } },
        },
        '#responseHeadersPolicy':: d.obj(help="\"The policy for managing response headers during proxying. Rewriting the 'Host' header is not supported.\""),
        responseHeadersPolicy: {
          '#set':: d.obj(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."'),
          set: {
            '#withName':: d.fn(help='"Name represents a key of a header"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withValue':: d.fn(help='"Value represents the value of a header specified by a key"', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#withRemove':: d.fn(help='"Remove specifies a list of HTTP header names to remove."', args=[d.arg(name='remove', type=d.T.array)]),
          withRemove(remove): { responseHeadersPolicy+: { remove: if std.isArray(v=remove) then remove else [remove] } },
          '#withRemoveMixin':: d.fn(help='"Remove specifies a list of HTTP header names to remove."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remove', type=d.T.array)]),
          withRemoveMixin(remove): { responseHeadersPolicy+: { remove+: if std.isArray(v=remove) then remove else [remove] } },
          '#withSet':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."', args=[d.arg(name='set', type=d.T.array)]),
          withSet(set): { responseHeadersPolicy+: { set: if std.isArray(v=set) then set else [set] } },
          '#withSetMixin':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='set', type=d.T.array)]),
          withSetMixin(set): { responseHeadersPolicy+: { set+: if std.isArray(v=set) then set else [set] } },
        },
        '#validation':: d.obj(help="\"UpstreamValidation defines how to verify the backend service's certificate\""),
        validation: {
          '#withCaSecret':: d.fn(help='"Name of the Kubernetes secret be used to validate the certificate presented by the backend"', args=[d.arg(name='caSecret', type=d.T.string)]),
          withCaSecret(caSecret): { validation+: { caSecret: caSecret } },
          '#withSubjectName':: d.fn(help="\"Key which is expected to be present in the 'subjectAltName' of the presented certificate\"", args=[d.arg(name='subjectName', type=d.T.string)]),
          withSubjectName(subjectName): { validation+: { subjectName: subjectName } },
        },
        '#withMirror':: d.fn(help='"If Mirror is true the Service will receive a read only mirror of the traffic for this route."', args=[d.arg(name='mirror', type=d.T.boolean)]),
        withMirror(mirror): { mirror: mirror },
        '#withName':: d.fn(help='"Name is the name of Kubernetes service to proxy traffic. Names defined here will be used to look up corresponding endpoints which contain the ips to route."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withPort':: d.fn(help='"Port (defined as Integer) to proxy traffic to since a service can have multiple defined."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { port: port },
        '#withProtocol':: d.fn(help='"Protocol may be used to specify (or override) the protocol used to reach this Service. Values may be tls, h2, h2c. If omitted, protocol-selection falls back on Service annotations."', args=[d.arg(name='protocol', type=d.T.string)]),
        withProtocol(protocol): { protocol: protocol },
        '#withWeight':: d.fn(help='"Weight defines percentage of traffic to balance traffic"', args=[d.arg(name='weight', type=d.T.integer)]),
        withWeight(weight): { weight: weight },
      },
      '#timeoutPolicy':: d.obj(help='"The timeout policy for this route."'),
      timeoutPolicy: {
        '#withIdle':: d.fn(help='"Timeout after which, if there are no active requests for this route, the connection between Envoy and the backend or Envoy and the external client will be closed. If not specified, there is no per-route idle timeout, though a connection manager-wide stream_idle_timeout default of 5m still applies."', args=[d.arg(name='idle', type=d.T.string)]),
        withIdle(idle): { timeoutPolicy+: { idle: idle } },
        '#withResponse':: d.fn(help="\"Timeout for receiving a response from the server after processing a request from client. If not supplied, Envoy's default value of 15s applies.\"", args=[d.arg(name='response', type=d.T.string)]),
        withResponse(response): { timeoutPolicy+: { response: response } },
      },
      '#withConditions':: d.fn(help='"Conditions are a set of rules that are applied to a Route. When applied, they are merged using AND, with one exception: There can be only one Prefix MatchCondition per Conditions slice. More than one Prefix, or contradictory Conditions, will make the route invalid."', args=[d.arg(name='conditions', type=d.T.array)]),
      withConditions(conditions): { conditions: if std.isArray(v=conditions) then conditions else [conditions] },
      '#withConditionsMixin':: d.fn(help='"Conditions are a set of rules that are applied to a Route. When applied, they are merged using AND, with one exception: There can be only one Prefix MatchCondition per Conditions slice. More than one Prefix, or contradictory Conditions, will make the route invalid."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='conditions', type=d.T.array)]),
      withConditionsMixin(conditions): { conditions+: if std.isArray(v=conditions) then conditions else [conditions] },
      '#withEnableWebsockets':: d.fn(help='"Enables websocket support for the route."', args=[d.arg(name='enableWebsockets', type=d.T.boolean)]),
      withEnableWebsockets(enableWebsockets): { enableWebsockets: enableWebsockets },
      '#withPermitInsecure':: d.fn(help='"Allow this path to respond to insecure requests over HTTP which are normally not permitted when a `virtualhost.tls` block is present."', args=[d.arg(name='permitInsecure', type=d.T.boolean)]),
      withPermitInsecure(permitInsecure): { permitInsecure: permitInsecure },
      '#withServices':: d.fn(help='"Services are the services to proxy traffic."', args=[d.arg(name='services', type=d.T.array)]),
      withServices(services): { services: if std.isArray(v=services) then services else [services] },
      '#withServicesMixin':: d.fn(help='"Services are the services to proxy traffic."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='services', type=d.T.array)]),
      withServicesMixin(services): { services+: if std.isArray(v=services) then services else [services] },
    },
    '#tcpproxy':: d.obj(help='"TCPProxy holds TCP proxy information."'),
    tcpproxy: {
      '#healthCheckPolicy':: d.obj(help='"The health check policy for this tcp proxy"'),
      healthCheckPolicy: {
        '#withHealthyThresholdCount':: d.fn(help='"The number of healthy health checks required before a host is marked healthy"', args=[d.arg(name='healthyThresholdCount', type=d.T.integer)]),
        withHealthyThresholdCount(healthyThresholdCount): { spec+: { tcpproxy+: { healthCheckPolicy+: { healthyThresholdCount: healthyThresholdCount } } } },
        '#withIntervalSeconds':: d.fn(help='"The interval (seconds) between health checks"', args=[d.arg(name='intervalSeconds', type=d.T.integer)]),
        withIntervalSeconds(intervalSeconds): { spec+: { tcpproxy+: { healthCheckPolicy+: { intervalSeconds: intervalSeconds } } } },
        '#withTimeoutSeconds':: d.fn(help='"The time to wait (seconds) for a health check response"', args=[d.arg(name='timeoutSeconds', type=d.T.integer)]),
        withTimeoutSeconds(timeoutSeconds): { spec+: { tcpproxy+: { healthCheckPolicy+: { timeoutSeconds: timeoutSeconds } } } },
        '#withUnhealthyThresholdCount':: d.fn(help='"The number of unhealthy health checks required before a host is marked unhealthy"', args=[d.arg(name='unhealthyThresholdCount', type=d.T.integer)]),
        withUnhealthyThresholdCount(unhealthyThresholdCount): { spec+: { tcpproxy+: { healthCheckPolicy+: { unhealthyThresholdCount: unhealthyThresholdCount } } } },
      },
      '#include':: d.obj(help='"Include specifies that this tcpproxy should be delegated to another HTTPProxy."'),
      include: {
        '#withName':: d.fn(help='"Name of the child HTTPProxy"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { tcpproxy+: { include+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the HTTPProxy to include. Defaults to the current namespace if not supplied."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { tcpproxy+: { include+: { namespace: namespace } } } },
      },
      '#includes':: d.obj(help='"IncludesDeprecated allow for specific routing configuration to be appended to another HTTPProxy in another namespace. \\n Exists due to a mistake when developing HTTPProxy and the field was marked plural when it should have been singular. This field should stay to not break backwards compatibility to v1 users."'),
      includes: {
        '#withName':: d.fn(help='"Name of the child HTTPProxy"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { tcpproxy+: { includes+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the HTTPProxy to include. Defaults to the current namespace if not supplied."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { tcpproxy+: { includes+: { namespace: namespace } } } },
      },
      '#loadBalancerPolicy':: d.obj(help='"The load balancing policy for the backend services."'),
      loadBalancerPolicy: {
        '#withStrategy':: d.fn(help='"Strategy specifies the policy used to balance requests across the pool of backend pods. Valid policy names are `Random`, `RoundRobin`, `WeightedLeastRequest`, `Random` and `Cookie`. If an unknown strategy name is specified or no policy is supplied, the default `RoundRobin` policy is used."', args=[d.arg(name='strategy', type=d.T.string)]),
        withStrategy(strategy): { spec+: { tcpproxy+: { loadBalancerPolicy+: { strategy: strategy } } } },
      },
      '#services':: d.obj(help='"Services are the services to proxy traffic"'),
      services: {
        '#requestHeadersPolicy':: d.obj(help="\"The policy for managing request headers during proxying. Rewriting the 'Host' header is not supported.\""),
        requestHeadersPolicy: {
          '#set':: d.obj(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."'),
          set: {
            '#withName':: d.fn(help='"Name represents a key of a header"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withValue':: d.fn(help='"Value represents the value of a header specified by a key"', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#withRemove':: d.fn(help='"Remove specifies a list of HTTP header names to remove."', args=[d.arg(name='remove', type=d.T.array)]),
          withRemove(remove): { requestHeadersPolicy+: { remove: if std.isArray(v=remove) then remove else [remove] } },
          '#withRemoveMixin':: d.fn(help='"Remove specifies a list of HTTP header names to remove."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remove', type=d.T.array)]),
          withRemoveMixin(remove): { requestHeadersPolicy+: { remove+: if std.isArray(v=remove) then remove else [remove] } },
          '#withSet':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."', args=[d.arg(name='set', type=d.T.array)]),
          withSet(set): { requestHeadersPolicy+: { set: if std.isArray(v=set) then set else [set] } },
          '#withSetMixin':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='set', type=d.T.array)]),
          withSetMixin(set): { requestHeadersPolicy+: { set+: if std.isArray(v=set) then set else [set] } },
        },
        '#responseHeadersPolicy':: d.obj(help="\"The policy for managing response headers during proxying. Rewriting the 'Host' header is not supported.\""),
        responseHeadersPolicy: {
          '#set':: d.obj(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."'),
          set: {
            '#withName':: d.fn(help='"Name represents a key of a header"', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withValue':: d.fn(help='"Value represents the value of a header specified by a key"', args=[d.arg(name='value', type=d.T.string)]),
            withValue(value): { value: value },
          },
          '#withRemove':: d.fn(help='"Remove specifies a list of HTTP header names to remove."', args=[d.arg(name='remove', type=d.T.array)]),
          withRemove(remove): { responseHeadersPolicy+: { remove: if std.isArray(v=remove) then remove else [remove] } },
          '#withRemoveMixin':: d.fn(help='"Remove specifies a list of HTTP header names to remove."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remove', type=d.T.array)]),
          withRemoveMixin(remove): { responseHeadersPolicy+: { remove+: if std.isArray(v=remove) then remove else [remove] } },
          '#withSet':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."', args=[d.arg(name='set', type=d.T.array)]),
          withSet(set): { responseHeadersPolicy+: { set: if std.isArray(v=set) then set else [set] } },
          '#withSetMixin':: d.fn(help='"Set specifies a list of HTTP header values that will be set in the HTTP header. If the header does not exist it will be added, otherwise it will be overwritten with the new value."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='set', type=d.T.array)]),
          withSetMixin(set): { responseHeadersPolicy+: { set+: if std.isArray(v=set) then set else [set] } },
        },
        '#validation':: d.obj(help="\"UpstreamValidation defines how to verify the backend service's certificate\""),
        validation: {
          '#withCaSecret':: d.fn(help='"Name of the Kubernetes secret be used to validate the certificate presented by the backend"', args=[d.arg(name='caSecret', type=d.T.string)]),
          withCaSecret(caSecret): { validation+: { caSecret: caSecret } },
          '#withSubjectName':: d.fn(help="\"Key which is expected to be present in the 'subjectAltName' of the presented certificate\"", args=[d.arg(name='subjectName', type=d.T.string)]),
          withSubjectName(subjectName): { validation+: { subjectName: subjectName } },
        },
        '#withMirror':: d.fn(help='"If Mirror is true the Service will receive a read only mirror of the traffic for this route."', args=[d.arg(name='mirror', type=d.T.boolean)]),
        withMirror(mirror): { mirror: mirror },
        '#withName':: d.fn(help='"Name is the name of Kubernetes service to proxy traffic. Names defined here will be used to look up corresponding endpoints which contain the ips to route."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withPort':: d.fn(help='"Port (defined as Integer) to proxy traffic to since a service can have multiple defined."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { port: port },
        '#withProtocol':: d.fn(help='"Protocol may be used to specify (or override) the protocol used to reach this Service. Values may be tls, h2, h2c. If omitted, protocol-selection falls back on Service annotations."', args=[d.arg(name='protocol', type=d.T.string)]),
        withProtocol(protocol): { protocol: protocol },
        '#withWeight':: d.fn(help='"Weight defines percentage of traffic to balance traffic"', args=[d.arg(name='weight', type=d.T.integer)]),
        withWeight(weight): { weight: weight },
      },
      '#withServices':: d.fn(help='"Services are the services to proxy traffic"', args=[d.arg(name='services', type=d.T.array)]),
      withServices(services): { spec+: { tcpproxy+: { services: if std.isArray(v=services) then services else [services] } } },
      '#withServicesMixin':: d.fn(help='"Services are the services to proxy traffic"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='services', type=d.T.array)]),
      withServicesMixin(services): { spec+: { tcpproxy+: { services+: if std.isArray(v=services) then services else [services] } } },
    },
    '#virtualhost':: d.obj(help='"Virtualhost appears at most once. If it is present, the object is considered to be a \\"root\\" HTTPProxy."'),
    virtualhost: {
      '#authorization':: d.obj(help='"This field configures an extension service to perform authorization for this virtual host. Authorization can only be configured on virtual hosts that have TLS enabled. If the TLS configuration requires client certificate /validation, the client certificate is always included in the authentication check request."'),
      authorization: {
        '#authPolicy':: d.obj(help='"AuthPolicy sets a default authorization policy for client requests. This policy will be used unless overridden by individual routes."'),
        authPolicy: {
          '#withContext':: d.fn(help='"Context is a set of key/value pairs that are sent to the authentication server in the check request. If a context is provided at an enclosing scope, the entries are merged such that the inner scope overrides matching keys from the outer scope."', args=[d.arg(name='context', type=d.T.object)]),
          withContext(context): { spec+: { virtualhost+: { authorization+: { authPolicy+: { context: context } } } } },
          '#withContextMixin':: d.fn(help='"Context is a set of key/value pairs that are sent to the authentication server in the check request. If a context is provided at an enclosing scope, the entries are merged such that the inner scope overrides matching keys from the outer scope."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='context', type=d.T.object)]),
          withContextMixin(context): { spec+: { virtualhost+: { authorization+: { authPolicy+: { context+: context } } } } },
          '#withDisabled':: d.fn(help='"When true, this field disables client request authentication for the scope of the policy."', args=[d.arg(name='disabled', type=d.T.boolean)]),
          withDisabled(disabled): { spec+: { virtualhost+: { authorization+: { authPolicy+: { disabled: disabled } } } } },
        },
        '#extensionRef':: d.obj(help='"ExtensionServiceRef specifies the extension resource that will authorize client requests."'),
        extensionRef: {
          '#withApiVersion':: d.fn(help='"API version of the referent. If this field is not specified, the default \\"projectcontour.io/v1alpha1\\" will be used"', args=[d.arg(name='apiVersion', type=d.T.string)]),
          withApiVersion(apiVersion): { spec+: { virtualhost+: { authorization+: { extensionRef+: { apiVersion: apiVersion } } } } },
          '#withName':: d.fn(help='"Name of the referent. \\n More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { virtualhost+: { authorization+: { extensionRef+: { name: name } } } } },
          '#withNamespace':: d.fn(help='"Namespace of the referent. If this field is not specifies, the namespace of the resource that targets the referent will be used. \\n More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { virtualhost+: { authorization+: { extensionRef+: { namespace: namespace } } } } },
        },
        '#withFailOpen':: d.fn(help='"If FailOpen is true, the client request is forwarded to the upstream service even if the authorization server fails to respond. This field should not be set in most cases. It is intended for use only while migrating applications from internal authorization to Contour external authorization."', args=[d.arg(name='failOpen', type=d.T.boolean)]),
        withFailOpen(failOpen): { spec+: { virtualhost+: { authorization+: { failOpen: failOpen } } } },
        '#withResponseTimeout':: d.fn(help='"ResponseTimeout configures maximum time to wait for a check response from the authorization server. Timeout durations are expressed in the Go [Duration format](https://godoc.org/time#ParseDuration). Valid time units are \\"ns\\", \\"us\\" (or \\"µs\\"), \\"ms\\", \\"s\\", \\"m\\", \\"h\\". The string \\"infinity\\" is also a valid input and specifies no timeout."', args=[d.arg(name='responseTimeout', type=d.T.string)]),
        withResponseTimeout(responseTimeout): { spec+: { virtualhost+: { authorization+: { responseTimeout: responseTimeout } } } },
      },
      '#corsPolicy':: d.obj(help='"Specifies the cross-origin policy to apply to the VirtualHost."'),
      corsPolicy: {
        '#withAllowCredentials':: d.fn(help='"Specifies whether the resource allows credentials."', args=[d.arg(name='allowCredentials', type=d.T.boolean)]),
        withAllowCredentials(allowCredentials): { spec+: { virtualhost+: { corsPolicy+: { allowCredentials: allowCredentials } } } },
        '#withAllowHeaders':: d.fn(help='"AllowHeaders specifies the content for the *access-control-allow-headers* header."', args=[d.arg(name='allowHeaders', type=d.T.array)]),
        withAllowHeaders(allowHeaders): { spec+: { virtualhost+: { corsPolicy+: { allowHeaders: if std.isArray(v=allowHeaders) then allowHeaders else [allowHeaders] } } } },
        '#withAllowHeadersMixin':: d.fn(help='"AllowHeaders specifies the content for the *access-control-allow-headers* header."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowHeaders', type=d.T.array)]),
        withAllowHeadersMixin(allowHeaders): { spec+: { virtualhost+: { corsPolicy+: { allowHeaders+: if std.isArray(v=allowHeaders) then allowHeaders else [allowHeaders] } } } },
        '#withAllowMethods':: d.fn(help='"AllowMethods specifies the content for the *access-control-allow-methods* header."', args=[d.arg(name='allowMethods', type=d.T.array)]),
        withAllowMethods(allowMethods): { spec+: { virtualhost+: { corsPolicy+: { allowMethods: if std.isArray(v=allowMethods) then allowMethods else [allowMethods] } } } },
        '#withAllowMethodsMixin':: d.fn(help='"AllowMethods specifies the content for the *access-control-allow-methods* header."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowMethods', type=d.T.array)]),
        withAllowMethodsMixin(allowMethods): { spec+: { virtualhost+: { corsPolicy+: { allowMethods+: if std.isArray(v=allowMethods) then allowMethods else [allowMethods] } } } },
        '#withAllowOrigin':: d.fn(help='"AllowOrigin specifies the origins that will be allowed to do CORS requests. \\"*\\" means allow any origin."', args=[d.arg(name='allowOrigin', type=d.T.array)]),
        withAllowOrigin(allowOrigin): { spec+: { virtualhost+: { corsPolicy+: { allowOrigin: if std.isArray(v=allowOrigin) then allowOrigin else [allowOrigin] } } } },
        '#withAllowOriginMixin':: d.fn(help='"AllowOrigin specifies the origins that will be allowed to do CORS requests. \\"*\\" means allow any origin."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowOrigin', type=d.T.array)]),
        withAllowOriginMixin(allowOrigin): { spec+: { virtualhost+: { corsPolicy+: { allowOrigin+: if std.isArray(v=allowOrigin) then allowOrigin else [allowOrigin] } } } },
        '#withExposeHeaders':: d.fn(help='"ExposeHeaders Specifies the content for the *access-control-expose-headers* header."', args=[d.arg(name='exposeHeaders', type=d.T.array)]),
        withExposeHeaders(exposeHeaders): { spec+: { virtualhost+: { corsPolicy+: { exposeHeaders: if std.isArray(v=exposeHeaders) then exposeHeaders else [exposeHeaders] } } } },
        '#withExposeHeadersMixin':: d.fn(help='"ExposeHeaders Specifies the content for the *access-control-expose-headers* header."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='exposeHeaders', type=d.T.array)]),
        withExposeHeadersMixin(exposeHeaders): { spec+: { virtualhost+: { corsPolicy+: { exposeHeaders+: if std.isArray(v=exposeHeaders) then exposeHeaders else [exposeHeaders] } } } },
        '#withMaxAge':: d.fn(help='"MaxAge indicates for how long the results of a preflight request can be cached. MaxAge durations are expressed in the Go [Duration format](https://godoc.org/time#ParseDuration). Valid time units are \\"ns\\", \\"us\\" (or \\"µs\\"), \\"ms\\", \\"s\\", \\"m\\", \\"h\\". Only positive values are allowed while 0 disables the cache requiring a preflight OPTIONS check for all cross-origin requests."', args=[d.arg(name='maxAge', type=d.T.string)]),
        withMaxAge(maxAge): { spec+: { virtualhost+: { corsPolicy+: { maxAge: maxAge } } } },
      },
      '#tls':: d.obj(help='"If present the fields describes TLS properties of the virtual host. The SNI names that will be matched on are described in fqdn, the tls.secretName secret must contain a certificate that itself contains a name that matches the FQDN."'),
      tls: {
        '#clientValidation':: d.obj(help='"ClientValidation defines how to verify the client certificate when an external client establishes a TLS connection to Envoy. \\n This setting: \\n 1. Enables TLS client certificate validation. 2. Requires clients to present a TLS certificate (i.e. not optional validation). 3. Specifies how the client certificate will be validated."'),
        clientValidation: {
          '#withCaSecret':: d.fn(help='"Name of a Kubernetes secret that contains a CA certificate bundle. The client certificate must validate against the certificates in the bundle."', args=[d.arg(name='caSecret', type=d.T.string)]),
          withCaSecret(caSecret): { spec+: { virtualhost+: { tls+: { clientValidation+: { caSecret: caSecret } } } } },
        },
        '#withEnableFallbackCertificate':: d.fn(help="\"EnableFallbackCertificate defines if the vhost should allow a default certificate to be applied which handles all requests which don't match the SNI defined in this vhost.\"", args=[d.arg(name='enableFallbackCertificate', type=d.T.boolean)]),
        withEnableFallbackCertificate(enableFallbackCertificate): { spec+: { virtualhost+: { tls+: { enableFallbackCertificate: enableFallbackCertificate } } } },
        '#withMinimumProtocolVersion':: d.fn(help='"Minimum TLS version this vhost should negotiate"', args=[d.arg(name='minimumProtocolVersion', type=d.T.string)]),
        withMinimumProtocolVersion(minimumProtocolVersion): { spec+: { virtualhost+: { tls+: { minimumProtocolVersion: minimumProtocolVersion } } } },
        '#withPassthrough':: d.fn(help='"Passthrough defines whether the encrypted TLS handshake will be passed through to the backing cluster. Either Passthrough or SecretName must be specified, but not both."', args=[d.arg(name='passthrough', type=d.T.boolean)]),
        withPassthrough(passthrough): { spec+: { virtualhost+: { tls+: { passthrough: passthrough } } } },
        '#withSecretName':: d.fn(help="\"SecretName is the name of a TLS secret in the current namespace. Either SecretName or Passthrough must be specified, but not both. If specified, the named secret must contain a matching certificate for the virtual host's FQDN.\"", args=[d.arg(name='secretName', type=d.T.string)]),
        withSecretName(secretName): { spec+: { virtualhost+: { tls+: { secretName: secretName } } } },
      },
      '#withFqdn':: d.fn(help='"The fully qualified domain name of the root of the ingress tree all leaves of the DAG rooted at this object relate to the fqdn."', args=[d.arg(name='fqdn', type=d.T.string)]),
      withFqdn(fqdn): { spec+: { virtualhost+: { fqdn: fqdn } } },
    },
    '#withIncludes':: d.fn(help='"Includes allow for specific routing configuration to be included from another HTTPProxy, possibly in another namespace."', args=[d.arg(name='includes', type=d.T.array)]),
    withIncludes(includes): { spec+: { includes: if std.isArray(v=includes) then includes else [includes] } },
    '#withIncludesMixin':: d.fn(help='"Includes allow for specific routing configuration to be included from another HTTPProxy, possibly in another namespace."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='includes', type=d.T.array)]),
    withIncludesMixin(includes): { spec+: { includes+: if std.isArray(v=includes) then includes else [includes] } },
    '#withRoutes':: d.fn(help='"Routes are the ingress routes. If TCPProxy is present, Routes is ignored."', args=[d.arg(name='routes', type=d.T.array)]),
    withRoutes(routes): { spec+: { routes: if std.isArray(v=routes) then routes else [routes] } },
    '#withRoutesMixin':: d.fn(help='"Routes are the ingress routes. If TCPProxy is present, Routes is ignored."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='routes', type=d.T.array)]),
    withRoutesMixin(routes): { spec+: { routes+: if std.isArray(v=routes) then routes else [routes] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
