{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='contourConfiguration', url='', help='"ContourConfiguration is the schema for a Contour instance."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of ContourConfiguration', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'projectcontour.io/v1alpha1',
    kind: 'ContourConfiguration',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"ContourConfigurationSpec represents a configuration of a Contour controller.\\nIt contains most of all the options that can be customized, the\\nother remaining options being command line flags."'),
  spec: {
    '#debug':: d.obj(help='"Debug contains parameters to enable debug logging\\nand debug interfaces inside Contour."'),
    debug: {
      '#withAddress':: d.fn(help="\"Defines the Contour debug address interface.\\nContour's default is \\\"127.0.0.1\\\".\"", args=[d.arg(name='address', type=d.T.string)]),
      withAddress(address): { spec+: { debug+: { address: address } } },
      '#withPort':: d.fn(help="\"Defines the Contour debug address port.\\nContour's default is 6060.\"", args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { debug+: { port: port } } },
    },
    '#envoy':: d.obj(help='"Envoy contains parameters for Envoy as well\\nas how to optionally configure a managed Envoy fleet."'),
    envoy: {
      '#clientCertificate':: d.obj(help='"ClientCertificate defines the namespace/name of the Kubernetes\\nsecret containing the client certificate and private key\\nto be used when establishing TLS connection to upstream\\ncluster."'),
      clientCertificate: {
        '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { envoy+: { clientCertificate+: { name: name } } } },
        '#withNamespace':: d.fn(help='', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { envoy+: { clientCertificate+: { namespace: namespace } } } },
      },
      '#cluster':: d.obj(help='"Cluster holds various configurable Envoy cluster values that can\\nbe set in the config file."'),
      cluster: {
        '#circuitBreakers':: d.obj(help='"GlobalCircuitBreakerDefaults specifies default circuit breaker budget across all services.\\nIf defined, this will be used as the default for all services."'),
        circuitBreakers: {
          '#withMaxConnections':: d.fn(help='"The maximum number of connections that a single Envoy instance allows to the Kubernetes Service; defaults to 1024."', args=[d.arg(name='maxConnections', type=d.T.integer)]),
          withMaxConnections(maxConnections): { spec+: { envoy+: { cluster+: { circuitBreakers+: { maxConnections: maxConnections } } } } },
          '#withMaxPendingRequests':: d.fn(help='"The maximum number of pending requests that a single Envoy instance allows to the Kubernetes Service; defaults to 1024."', args=[d.arg(name='maxPendingRequests', type=d.T.integer)]),
          withMaxPendingRequests(maxPendingRequests): { spec+: { envoy+: { cluster+: { circuitBreakers+: { maxPendingRequests: maxPendingRequests } } } } },
          '#withMaxRequests':: d.fn(help='"The maximum parallel requests a single Envoy instance allows to the Kubernetes Service; defaults to 1024"', args=[d.arg(name='maxRequests', type=d.T.integer)]),
          withMaxRequests(maxRequests): { spec+: { envoy+: { cluster+: { circuitBreakers+: { maxRequests: maxRequests } } } } },
          '#withMaxRetries':: d.fn(help='"The maximum number of parallel retries a single Envoy instance allows to the Kubernetes Service; defaults to 3."', args=[d.arg(name='maxRetries', type=d.T.integer)]),
          withMaxRetries(maxRetries): { spec+: { envoy+: { cluster+: { circuitBreakers+: { maxRetries: maxRetries } } } } },
          '#withPerHostMaxConnections':: d.fn(help='"PerHostMaxConnections is the maximum number of connections\\nthat Envoy will allow to each individual host in a cluster."', args=[d.arg(name='perHostMaxConnections', type=d.T.integer)]),
          withPerHostMaxConnections(perHostMaxConnections): { spec+: { envoy+: { cluster+: { circuitBreakers+: { perHostMaxConnections: perHostMaxConnections } } } } },
        },
        '#upstreamTLS':: d.obj(help='"UpstreamTLS contains the TLS policy parameters for upstream connections"'),
        upstreamTLS: {
          '#withCipherSuites':: d.fn(help="\"CipherSuites defines the TLS ciphers to be supported by Envoy TLS\\nlisteners when negotiating TLS 1.2. Ciphers are validated against the\\nset that Envoy supports by default. This parameter should only be used\\nby advanced users. Note that these will be ignored when TLS 1.3 is in\\nuse.\\nThis field is optional; when it is undefined, a Contour-managed ciphersuite list\\nwill be used, which may be updated to keep it secure.\\nContour's default list is:\\n  - \\\"[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]\\\"\\n  - \\\"[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]\\\"\\n  - \\\"ECDHE-ECDSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-RSA-AES256-GCM-SHA384\\\"\\nCiphers provided are validated against the following list:\\n  - \\\"[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]\\\"\\n  - \\\"[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]\\\"\\n  - \\\"ECDHE-ECDSA-AES128-GCM-SHA256\\\"\\n  - \\\"ECDHE-RSA-AES128-GCM-SHA256\\\"\\n  - \\\"ECDHE-ECDSA-AES128-SHA\\\"\\n  - \\\"ECDHE-RSA-AES128-SHA\\\"\\n  - \\\"AES128-GCM-SHA256\\\"\\n  - \\\"AES128-SHA\\\"\\n  - \\\"ECDHE-ECDSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-RSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-ECDSA-AES256-SHA\\\"\\n  - \\\"ECDHE-RSA-AES256-SHA\\\"\\n  - \\\"AES256-GCM-SHA384\\\"\\n  - \\\"AES256-SHA\\\"\\nContour recommends leaving this undefined unless you are sure you must.\\nSee: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlsparameters\\nNote: This list is a superset of what is valid for stock Envoy builds and those using BoringSSL FIPS.\"", args=[d.arg(name='cipherSuites', type=d.T.array)]),
          withCipherSuites(cipherSuites): { spec+: { envoy+: { cluster+: { upstreamTLS+: { cipherSuites: if std.isArray(v=cipherSuites) then cipherSuites else [cipherSuites] } } } } },
          '#withCipherSuitesMixin':: d.fn(help="\"CipherSuites defines the TLS ciphers to be supported by Envoy TLS\\nlisteners when negotiating TLS 1.2. Ciphers are validated against the\\nset that Envoy supports by default. This parameter should only be used\\nby advanced users. Note that these will be ignored when TLS 1.3 is in\\nuse.\\nThis field is optional; when it is undefined, a Contour-managed ciphersuite list\\nwill be used, which may be updated to keep it secure.\\nContour's default list is:\\n  - \\\"[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]\\\"\\n  - \\\"[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]\\\"\\n  - \\\"ECDHE-ECDSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-RSA-AES256-GCM-SHA384\\\"\\nCiphers provided are validated against the following list:\\n  - \\\"[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]\\\"\\n  - \\\"[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]\\\"\\n  - \\\"ECDHE-ECDSA-AES128-GCM-SHA256\\\"\\n  - \\\"ECDHE-RSA-AES128-GCM-SHA256\\\"\\n  - \\\"ECDHE-ECDSA-AES128-SHA\\\"\\n  - \\\"ECDHE-RSA-AES128-SHA\\\"\\n  - \\\"AES128-GCM-SHA256\\\"\\n  - \\\"AES128-SHA\\\"\\n  - \\\"ECDHE-ECDSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-RSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-ECDSA-AES256-SHA\\\"\\n  - \\\"ECDHE-RSA-AES256-SHA\\\"\\n  - \\\"AES256-GCM-SHA384\\\"\\n  - \\\"AES256-SHA\\\"\\nContour recommends leaving this undefined unless you are sure you must.\\nSee: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlsparameters\\nNote: This list is a superset of what is valid for stock Envoy builds and those using BoringSSL FIPS.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='cipherSuites', type=d.T.array)]),
          withCipherSuitesMixin(cipherSuites): { spec+: { envoy+: { cluster+: { upstreamTLS+: { cipherSuites+: if std.isArray(v=cipherSuites) then cipherSuites else [cipherSuites] } } } } },
          '#withMaximumProtocolVersion':: d.fn(help='"MaximumProtocolVersion is the maximum TLS version this vhost should\\nnegotiate.\\nValues: `1.2`, `1.3`(default).\\nOther values will produce an error."', args=[d.arg(name='maximumProtocolVersion', type=d.T.string)]),
          withMaximumProtocolVersion(maximumProtocolVersion): { spec+: { envoy+: { cluster+: { upstreamTLS+: { maximumProtocolVersion: maximumProtocolVersion } } } } },
          '#withMinimumProtocolVersion':: d.fn(help='"MinimumProtocolVersion is the minimum TLS version this vhost should\\nnegotiate.\\nValues: `1.2` (default), `1.3`.\\nOther values will produce an error."', args=[d.arg(name='minimumProtocolVersion', type=d.T.string)]),
          withMinimumProtocolVersion(minimumProtocolVersion): { spec+: { envoy+: { cluster+: { upstreamTLS+: { minimumProtocolVersion: minimumProtocolVersion } } } } },
        },
        '#withDnsLookupFamily':: d.fn(help='"DNSLookupFamily defines how external names are looked up\\nWhen configured as V4, the DNS resolver will only perform a lookup\\nfor addresses in the IPv4 family. If V6 is configured, the DNS resolver\\nwill only perform a lookup for addresses in the IPv6 family.\\nIf AUTO is configured, the DNS resolver will first perform a lookup\\nfor addresses in the IPv6 family and fallback to a lookup for addresses\\nin the IPv4 family. If ALL is specified, the DNS resolver will perform a lookup for\\nboth IPv4 and IPv6 families, and return all resolved addresses.\\nWhen this is used, Happy Eyeballs will be enabled for upstream connections.\\nRefer to Happy Eyeballs Support for more information.\\nNote: This only applies to externalName clusters.\\nSee https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto.html#envoy-v3-api-enum-config-cluster-v3-cluster-dnslookupfamily\\nfor more information.\\nValues: `auto` (default), `v4`, `v6`, `all`.\\nOther values will produce an error."', args=[d.arg(name='dnsLookupFamily', type=d.T.string)]),
        withDnsLookupFamily(dnsLookupFamily): { spec+: { envoy+: { cluster+: { dnsLookupFamily: dnsLookupFamily } } } },
        '#withMaxRequestsPerConnection':: d.fn(help='"Defines the maximum requests for upstream connections. If not specified, there is no limit.\\nsee https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-httpprotocoloptions\\nfor more information."', args=[d.arg(name='maxRequestsPerConnection', type=d.T.integer)]),
        withMaxRequestsPerConnection(maxRequestsPerConnection): { spec+: { envoy+: { cluster+: { maxRequestsPerConnection: maxRequestsPerConnection } } } },
        '#withPer-Connection-Buffer-Limit-Bytes':: d.fn(help='"Defines the soft limit on size of the cluster’s new connection read and write buffers in bytes.\\nIf unspecified, an implementation defined default is applied (1MiB).\\nsee https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-per-connection-buffer-limit-bytes\\nfor more information."', args=[d.arg(name='per_connection_buffer_limit_bytes', type=d.T.integer)]),
        'withPer-Connection-Buffer-Limit-Bytes'(per_connection_buffer_limit_bytes): { spec+: { envoy+: { cluster+: { 'per-connection-buffer-limit-bytes': per_connection_buffer_limit_bytes } } } },
      },
      '#health':: d.obj(help="\"Health defines the endpoint Envoy uses to serve health checks.\\nContour's default is { address: \\\"0.0.0.0\\\", port: 8002 }.\""),
      health: {
        '#withAddress':: d.fn(help='"Defines the health address interface."', args=[d.arg(name='address', type=d.T.string)]),
        withAddress(address): { spec+: { envoy+: { health+: { address: address } } } },
        '#withPort':: d.fn(help='"Defines the health port."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { spec+: { envoy+: { health+: { port: port } } } },
      },
      '#http':: d.obj(help="\"Defines the HTTP Listener for Envoy.\\nContour's default is { address: \\\"0.0.0.0\\\", port: 8080, accessLog: \\\"/dev/stdout\\\" }.\""),
      http: {
        '#withAccessLog':: d.fn(help='"AccessLog defines where Envoy logs are outputted for this listener."', args=[d.arg(name='accessLog', type=d.T.string)]),
        withAccessLog(accessLog): { spec+: { envoy+: { http+: { accessLog: accessLog } } } },
        '#withAddress':: d.fn(help='"Defines an Envoy Listener Address."', args=[d.arg(name='address', type=d.T.string)]),
        withAddress(address): { spec+: { envoy+: { http+: { address: address } } } },
        '#withPort':: d.fn(help='"Defines an Envoy listener Port."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { spec+: { envoy+: { http+: { port: port } } } },
      },
      '#https':: d.obj(help="\"Defines the HTTPS Listener for Envoy.\\nContour's default is { address: \\\"0.0.0.0\\\", port: 8443, accessLog: \\\"/dev/stdout\\\" }.\""),
      https: {
        '#withAccessLog':: d.fn(help='"AccessLog defines where Envoy logs are outputted for this listener."', args=[d.arg(name='accessLog', type=d.T.string)]),
        withAccessLog(accessLog): { spec+: { envoy+: { https+: { accessLog: accessLog } } } },
        '#withAddress':: d.fn(help='"Defines an Envoy Listener Address."', args=[d.arg(name='address', type=d.T.string)]),
        withAddress(address): { spec+: { envoy+: { https+: { address: address } } } },
        '#withPort':: d.fn(help='"Defines an Envoy listener Port."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { spec+: { envoy+: { https+: { port: port } } } },
      },
      '#listener':: d.obj(help='"Listener hold various configurable Envoy listener values."'),
      listener: {
        '#socketOptions':: d.obj(help='"SocketOptions defines configurable socket options for the listeners.\\nSingle set of options are applied to all listeners."'),
        socketOptions: {
          '#withTos':: d.fn(help='"Defines the value for IPv4 TOS field (including 6 bit DSCP field) for IP packets originating from Envoy listeners.\\nSingle value is applied to all listeners.\\nIf listeners are bound to IPv6-only addresses, setting this option will cause an error."', args=[d.arg(name='tos', type=d.T.integer)]),
          withTos(tos): { spec+: { envoy+: { listener+: { socketOptions+: { tos: tos } } } } },
          '#withTrafficClass':: d.fn(help='"Defines the value for IPv6 Traffic Class field (including 6 bit DSCP field) for IP packets originating from the Envoy listeners.\\nSingle value is applied to all listeners.\\nIf listeners are bound to IPv4-only addresses, setting this option will cause an error."', args=[d.arg(name='trafficClass', type=d.T.integer)]),
          withTrafficClass(trafficClass): { spec+: { envoy+: { listener+: { socketOptions+: { trafficClass: trafficClass } } } } },
        },
        '#tls':: d.obj(help='"TLS holds various configurable Envoy TLS listener values."'),
        tls: {
          '#withCipherSuites':: d.fn(help="\"CipherSuites defines the TLS ciphers to be supported by Envoy TLS\\nlisteners when negotiating TLS 1.2. Ciphers are validated against the\\nset that Envoy supports by default. This parameter should only be used\\nby advanced users. Note that these will be ignored when TLS 1.3 is in\\nuse.\\nThis field is optional; when it is undefined, a Contour-managed ciphersuite list\\nwill be used, which may be updated to keep it secure.\\nContour's default list is:\\n  - \\\"[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]\\\"\\n  - \\\"[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]\\\"\\n  - \\\"ECDHE-ECDSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-RSA-AES256-GCM-SHA384\\\"\\nCiphers provided are validated against the following list:\\n  - \\\"[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]\\\"\\n  - \\\"[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]\\\"\\n  - \\\"ECDHE-ECDSA-AES128-GCM-SHA256\\\"\\n  - \\\"ECDHE-RSA-AES128-GCM-SHA256\\\"\\n  - \\\"ECDHE-ECDSA-AES128-SHA\\\"\\n  - \\\"ECDHE-RSA-AES128-SHA\\\"\\n  - \\\"AES128-GCM-SHA256\\\"\\n  - \\\"AES128-SHA\\\"\\n  - \\\"ECDHE-ECDSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-RSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-ECDSA-AES256-SHA\\\"\\n  - \\\"ECDHE-RSA-AES256-SHA\\\"\\n  - \\\"AES256-GCM-SHA384\\\"\\n  - \\\"AES256-SHA\\\"\\nContour recommends leaving this undefined unless you are sure you must.\\nSee: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlsparameters\\nNote: This list is a superset of what is valid for stock Envoy builds and those using BoringSSL FIPS.\"", args=[d.arg(name='cipherSuites', type=d.T.array)]),
          withCipherSuites(cipherSuites): { spec+: { envoy+: { listener+: { tls+: { cipherSuites: if std.isArray(v=cipherSuites) then cipherSuites else [cipherSuites] } } } } },
          '#withCipherSuitesMixin':: d.fn(help="\"CipherSuites defines the TLS ciphers to be supported by Envoy TLS\\nlisteners when negotiating TLS 1.2. Ciphers are validated against the\\nset that Envoy supports by default. This parameter should only be used\\nby advanced users. Note that these will be ignored when TLS 1.3 is in\\nuse.\\nThis field is optional; when it is undefined, a Contour-managed ciphersuite list\\nwill be used, which may be updated to keep it secure.\\nContour's default list is:\\n  - \\\"[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]\\\"\\n  - \\\"[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]\\\"\\n  - \\\"ECDHE-ECDSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-RSA-AES256-GCM-SHA384\\\"\\nCiphers provided are validated against the following list:\\n  - \\\"[ECDHE-ECDSA-AES128-GCM-SHA256|ECDHE-ECDSA-CHACHA20-POLY1305]\\\"\\n  - \\\"[ECDHE-RSA-AES128-GCM-SHA256|ECDHE-RSA-CHACHA20-POLY1305]\\\"\\n  - \\\"ECDHE-ECDSA-AES128-GCM-SHA256\\\"\\n  - \\\"ECDHE-RSA-AES128-GCM-SHA256\\\"\\n  - \\\"ECDHE-ECDSA-AES128-SHA\\\"\\n  - \\\"ECDHE-RSA-AES128-SHA\\\"\\n  - \\\"AES128-GCM-SHA256\\\"\\n  - \\\"AES128-SHA\\\"\\n  - \\\"ECDHE-ECDSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-RSA-AES256-GCM-SHA384\\\"\\n  - \\\"ECDHE-ECDSA-AES256-SHA\\\"\\n  - \\\"ECDHE-RSA-AES256-SHA\\\"\\n  - \\\"AES256-GCM-SHA384\\\"\\n  - \\\"AES256-SHA\\\"\\nContour recommends leaving this undefined unless you are sure you must.\\nSee: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlsparameters\\nNote: This list is a superset of what is valid for stock Envoy builds and those using BoringSSL FIPS.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='cipherSuites', type=d.T.array)]),
          withCipherSuitesMixin(cipherSuites): { spec+: { envoy+: { listener+: { tls+: { cipherSuites+: if std.isArray(v=cipherSuites) then cipherSuites else [cipherSuites] } } } } },
          '#withMaximumProtocolVersion':: d.fn(help='"MaximumProtocolVersion is the maximum TLS version this vhost should\\nnegotiate.\\nValues: `1.2`, `1.3`(default).\\nOther values will produce an error."', args=[d.arg(name='maximumProtocolVersion', type=d.T.string)]),
          withMaximumProtocolVersion(maximumProtocolVersion): { spec+: { envoy+: { listener+: { tls+: { maximumProtocolVersion: maximumProtocolVersion } } } } },
          '#withMinimumProtocolVersion':: d.fn(help='"MinimumProtocolVersion is the minimum TLS version this vhost should\\nnegotiate.\\nValues: `1.2` (default), `1.3`.\\nOther values will produce an error."', args=[d.arg(name='minimumProtocolVersion', type=d.T.string)]),
          withMinimumProtocolVersion(minimumProtocolVersion): { spec+: { envoy+: { listener+: { tls+: { minimumProtocolVersion: minimumProtocolVersion } } } } },
        },
        '#withConnectionBalancer':: d.fn(help='"ConnectionBalancer. If the value is exact, the listener will use the exact connection balancer\\nSee https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/listener.proto#envoy-api-msg-listener-connectionbalanceconfig\\nfor more information.\\nValues: (empty string): use the default ConnectionBalancer, `exact`: use the Exact ConnectionBalancer.\\nOther values will produce an error."', args=[d.arg(name='connectionBalancer', type=d.T.string)]),
        withConnectionBalancer(connectionBalancer): { spec+: { envoy+: { listener+: { connectionBalancer: connectionBalancer } } } },
        '#withDisableAllowChunkedLength':: d.fn(help="\"DisableAllowChunkedLength disables the RFC-compliant Envoy behavior to\\nstrip the \\\"Content-Length\\\" header if \\\"Transfer-Encoding: chunked\\\" is\\nalso set. This is an emergency off-switch to revert back to Envoy's\\ndefault behavior in case of failures. Please file an issue if failures\\nare encountered.\\nSee: https://github.com/projectcontour/contour/issues/3221\\nContour's default is false.\"", args=[d.arg(name='disableAllowChunkedLength', type=d.T.boolean)]),
        withDisableAllowChunkedLength(disableAllowChunkedLength): { spec+: { envoy+: { listener+: { disableAllowChunkedLength: disableAllowChunkedLength } } } },
        '#withDisableMergeSlashes':: d.fn(help="\"DisableMergeSlashes disables Envoy's non-standard merge_slashes path transformation option\\nwhich strips duplicate slashes from request URL paths.\\nContour's default is false.\"", args=[d.arg(name='disableMergeSlashes', type=d.T.boolean)]),
        withDisableMergeSlashes(disableMergeSlashes): { spec+: { envoy+: { listener+: { disableMergeSlashes: disableMergeSlashes } } } },
        '#withHttpMaxConcurrentStreams':: d.fn(help='"Defines the value for SETTINGS_MAX_CONCURRENT_STREAMS Envoy will advertise in the\\nSETTINGS frame in HTTP/2 connections and the limit for concurrent streams allowed\\nfor a peer on a single HTTP/2 connection. It is recommended to not set this lower\\nthan 100 but this field can be used to bound resource usage by HTTP/2 connections\\nand mitigate attacks like CVE-2023-44487. The default value when this is not set is\\nunlimited."', args=[d.arg(name='httpMaxConcurrentStreams', type=d.T.integer)]),
        withHttpMaxConcurrentStreams(httpMaxConcurrentStreams): { spec+: { envoy+: { listener+: { httpMaxConcurrentStreams: httpMaxConcurrentStreams } } } },
        '#withMaxConnectionsPerListener':: d.fn(help='"Defines the limit on number of active connections to a listener. The limit is applied\\nper listener. The default value when this is not set is unlimited."', args=[d.arg(name='maxConnectionsPerListener', type=d.T.integer)]),
        withMaxConnectionsPerListener(maxConnectionsPerListener): { spec+: { envoy+: { listener+: { maxConnectionsPerListener: maxConnectionsPerListener } } } },
        '#withMaxRequestsPerConnection':: d.fn(help='"Defines the maximum requests for downstream connections. If not specified, there is no limit.\\nsee https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-httpprotocoloptions\\nfor more information."', args=[d.arg(name='maxRequestsPerConnection', type=d.T.integer)]),
        withMaxRequestsPerConnection(maxRequestsPerConnection): { spec+: { envoy+: { listener+: { maxRequestsPerConnection: maxRequestsPerConnection } } } },
        '#withMaxRequestsPerIOCycle':: d.fn(help='"Defines the limit on number of HTTP requests that Envoy will process from a single\\nconnection in a single I/O cycle. Requests over this limit are processed in subsequent\\nI/O cycles. Can be used as a mitigation for CVE-2023-44487 when abusive traffic is\\ndetected. Configures the http.max_requests_per_io_cycle Envoy runtime setting. The default\\nvalue when this is not set is no limit."', args=[d.arg(name='maxRequestsPerIOCycle', type=d.T.integer)]),
        withMaxRequestsPerIOCycle(maxRequestsPerIOCycle): { spec+: { envoy+: { listener+: { maxRequestsPerIOCycle: maxRequestsPerIOCycle } } } },
        '#withPer-Connection-Buffer-Limit-Bytes':: d.fn(help='"Defines the soft limit on size of the listener’s new connection read and write buffers in bytes.\\nIf unspecified, an implementation defined default is applied (1MiB).\\nsee https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-per-connection-buffer-limit-bytes\\nfor more information."', args=[d.arg(name='per_connection_buffer_limit_bytes', type=d.T.integer)]),
        'withPer-Connection-Buffer-Limit-Bytes'(per_connection_buffer_limit_bytes): { spec+: { envoy+: { listener+: { 'per-connection-buffer-limit-bytes': per_connection_buffer_limit_bytes } } } },
        '#withServerHeaderTransformation':: d.fn(help="\"Defines the action to be applied to the Server header on the response path.\\nWhen configured as overwrite, overwrites any Server header with \\\"envoy\\\".\\nWhen configured as append_if_absent, if a Server header is present, pass it through, otherwise set it to \\\"envoy\\\".\\nWhen configured as pass_through, pass through the value of the Server header, and do not append a header if none is present.\\nValues: `overwrite` (default), `append_if_absent`, `pass_through`\\nOther values will produce an error.\\nContour's default is overwrite.\"", args=[d.arg(name='serverHeaderTransformation', type=d.T.string)]),
        withServerHeaderTransformation(serverHeaderTransformation): { spec+: { envoy+: { listener+: { serverHeaderTransformation: serverHeaderTransformation } } } },
        '#withUseProxyProtocol':: d.fn(help="\"Use PROXY protocol for all listeners.\\nContour's default is false.\"", args=[d.arg(name='useProxyProtocol', type=d.T.boolean)]),
        withUseProxyProtocol(useProxyProtocol): { spec+: { envoy+: { listener+: { useProxyProtocol: useProxyProtocol } } } },
      },
      '#logging':: d.obj(help="\"Logging defines how Envoy's logs can be configured.\""),
      logging: {
        '#withAccessLogFormat':: d.fn(help='"AccessLogFormat sets the global access log format.\\nValues: `envoy` (default), `json`.\\nOther values will produce an error."', args=[d.arg(name='accessLogFormat', type=d.T.string)]),
        withAccessLogFormat(accessLogFormat): { spec+: { envoy+: { logging+: { accessLogFormat: accessLogFormat } } } },
        '#withAccessLogFormatString':: d.fn(help="\"AccessLogFormatString sets the access log format when format is set to `envoy`.\\nWhen empty, Envoy's default format is used.\"", args=[d.arg(name='accessLogFormatString', type=d.T.string)]),
        withAccessLogFormatString(accessLogFormatString): { spec+: { envoy+: { logging+: { accessLogFormatString: accessLogFormatString } } } },
        '#withAccessLogJSONFields':: d.fn(help='"AccessLogJSONFields sets the fields that JSON logging will\\noutput when AccessLogFormat is json."', args=[d.arg(name='accessLogJSONFields', type=d.T.array)]),
        withAccessLogJSONFields(accessLogJSONFields): { spec+: { envoy+: { logging+: { accessLogJSONFields: if std.isArray(v=accessLogJSONFields) then accessLogJSONFields else [accessLogJSONFields] } } } },
        '#withAccessLogJSONFieldsMixin':: d.fn(help='"AccessLogJSONFields sets the fields that JSON logging will\\noutput when AccessLogFormat is json."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='accessLogJSONFields', type=d.T.array)]),
        withAccessLogJSONFieldsMixin(accessLogJSONFields): { spec+: { envoy+: { logging+: { accessLogJSONFields+: if std.isArray(v=accessLogJSONFields) then accessLogJSONFields else [accessLogJSONFields] } } } },
        '#withAccessLogLevel':: d.fn(help='"AccessLogLevel sets the verbosity level of the access log.\\nValues: `info` (default, all requests are logged), `error` (all non-success requests, i.e. 300+ response code, are logged), `critical` (all 5xx requests are logged) and `disabled`.\\nOther values will produce an error."', args=[d.arg(name='accessLogLevel', type=d.T.string)]),
        withAccessLogLevel(accessLogLevel): { spec+: { envoy+: { logging+: { accessLogLevel: accessLogLevel } } } },
      },
      '#metrics':: d.obj(help="\"Metrics defines the endpoint Envoy uses to serve metrics.\\nContour's default is { address: \\\"0.0.0.0\\\", port: 8002 }.\""),
      metrics: {
        '#tls':: d.obj(help='"TLS holds TLS file config details.\\nMetrics and health endpoints cannot have same port number when metrics is served over HTTPS."'),
        tls: {
          '#withCaFile':: d.fn(help='"CA filename."', args=[d.arg(name='caFile', type=d.T.string)]),
          withCaFile(caFile): { spec+: { envoy+: { metrics+: { tls+: { caFile: caFile } } } } },
          '#withCertFile':: d.fn(help='"Client certificate filename."', args=[d.arg(name='certFile', type=d.T.string)]),
          withCertFile(certFile): { spec+: { envoy+: { metrics+: { tls+: { certFile: certFile } } } } },
          '#withKeyFile':: d.fn(help='"Client key filename."', args=[d.arg(name='keyFile', type=d.T.string)]),
          withKeyFile(keyFile): { spec+: { envoy+: { metrics+: { tls+: { keyFile: keyFile } } } } },
        },
        '#withAddress':: d.fn(help='"Defines the metrics address interface."', args=[d.arg(name='address', type=d.T.string)]),
        withAddress(address): { spec+: { envoy+: { metrics+: { address: address } } } },
        '#withPort':: d.fn(help='"Defines the metrics port."', args=[d.arg(name='port', type=d.T.integer)]),
        withPort(port): { spec+: { envoy+: { metrics+: { port: port } } } },
      },
      '#network':: d.obj(help='"Network holds various configurable Envoy network values."'),
      network: {
        '#withAdminPort':: d.fn(help="\"Configure the port used to access the Envoy Admin interface.\\nIf configured to port \\\"0\\\" then the admin interface is disabled.\\nContour's default is 9001.\"", args=[d.arg(name='adminPort', type=d.T.integer)]),
        withAdminPort(adminPort): { spec+: { envoy+: { network+: { adminPort: adminPort } } } },
        '#withNumTrustedHops':: d.fn(help="\"XffNumTrustedHops defines the number of additional ingress proxy hops from the\\nright side of the x-forwarded-for HTTP header to trust when determining the origin\\nclient’s IP address.\\nSee https://www.envoyproxy.io/docs/envoy/v1.17.0/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto?highlight=xff_num_trusted_hops\\nfor more information.\\nContour's default is 0.\"", args=[d.arg(name='numTrustedHops', type=d.T.integer)]),
        withNumTrustedHops(numTrustedHops): { spec+: { envoy+: { network+: { numTrustedHops: numTrustedHops } } } },
      },
      '#service':: d.obj(help="\"Service holds Envoy service parameters for setting Ingress status.\\nContour's default is { namespace: \\\"projectcontour\\\", name: \\\"envoy\\\" }.\""),
      service: {
        '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { envoy+: { service+: { name: name } } } },
        '#withNamespace':: d.fn(help='', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { envoy+: { service+: { namespace: namespace } } } },
      },
      '#timeouts':: d.obj(help='"Timeouts holds various configurable timeouts that can\\nbe set in the config file."'),
      timeouts: {
        '#withConnectTimeout':: d.fn(help='"ConnectTimeout defines how long the proxy should wait when establishing connection to upstream service.\\nIf not set, a default value of 2 seconds will be used.\\nSee https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-connect-timeout\\nfor more information."', args=[d.arg(name='connectTimeout', type=d.T.string)]),
        withConnectTimeout(connectTimeout): { spec+: { envoy+: { timeouts+: { connectTimeout: connectTimeout } } } },
        '#withConnectionIdleTimeout':: d.fn(help='"ConnectionIdleTimeout defines how long the proxy should wait while there are\\nno active requests (for HTTP/1.1) or streams (for HTTP/2) before terminating\\nan HTTP connection. Set to \\"infinity\\" to disable the timeout entirely.\\nSee https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-idle-timeout\\nfor more information."', args=[d.arg(name='connectionIdleTimeout', type=d.T.string)]),
        withConnectionIdleTimeout(connectionIdleTimeout): { spec+: { envoy+: { timeouts+: { connectionIdleTimeout: connectionIdleTimeout } } } },
        '#withConnectionShutdownGracePeriod':: d.fn(help='"ConnectionShutdownGracePeriod defines how long the proxy will wait between sending an\\ninitial GOAWAY frame and a second, final GOAWAY frame when terminating an HTTP/2 connection.\\nDuring this grace period, the proxy will continue to respond to new streams. After the final\\nGOAWAY frame has been sent, the proxy will refuse new streams.\\nSee https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-drain-timeout\\nfor more information."', args=[d.arg(name='connectionShutdownGracePeriod', type=d.T.string)]),
        withConnectionShutdownGracePeriod(connectionShutdownGracePeriod): { spec+: { envoy+: { timeouts+: { connectionShutdownGracePeriod: connectionShutdownGracePeriod } } } },
        '#withDelayedCloseTimeout':: d.fn(help="\"DelayedCloseTimeout defines how long envoy will wait, once connection\\nclose processing has been initiated, for the downstream peer to close\\nthe connection before Envoy closes the socket associated with the connection.\\nSetting this timeout to 'infinity' will disable it, equivalent to setting it to '0'\\nin Envoy. Leaving it unset will result in the Envoy default value being used.\\nSee https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-delayed-close-timeout\\nfor more information.\"", args=[d.arg(name='delayedCloseTimeout', type=d.T.string)]),
        withDelayedCloseTimeout(delayedCloseTimeout): { spec+: { envoy+: { timeouts+: { delayedCloseTimeout: delayedCloseTimeout } } } },
        '#withMaxConnectionDuration':: d.fn(help='"MaxConnectionDuration defines the maximum period of time after an HTTP connection\\nhas been established from the client to the proxy before it is closed by the proxy,\\nregardless of whether there has been activity or not. Omit or set to \\"infinity\\" for\\nno max duration.\\nSee https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-httpprotocoloptions-max-connection-duration\\nfor more information."', args=[d.arg(name='maxConnectionDuration', type=d.T.string)]),
        withMaxConnectionDuration(maxConnectionDuration): { spec+: { envoy+: { timeouts+: { maxConnectionDuration: maxConnectionDuration } } } },
        '#withRequestTimeout':: d.fn(help='"RequestTimeout sets the client request timeout globally for Contour. Note that\\nthis is a timeout for the entire request, not an idle timeout. Omit or set to\\n\\"infinity\\" to disable the timeout entirely.\\nSee https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-request-timeout\\nfor more information."', args=[d.arg(name='requestTimeout', type=d.T.string)]),
        withRequestTimeout(requestTimeout): { spec+: { envoy+: { timeouts+: { requestTimeout: requestTimeout } } } },
        '#withStreamIdleTimeout':: d.fn(help='"StreamIdleTimeout defines how long the proxy should wait while there is no\\nrequest activity (for HTTP/1.1) or stream activity (for HTTP/2) before\\nterminating the HTTP request or stream. Set to \\"infinity\\" to disable the\\ntimeout entirely.\\nSee https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-stream-idle-timeout\\nfor more information."', args=[d.arg(name='streamIdleTimeout', type=d.T.string)]),
        withStreamIdleTimeout(streamIdleTimeout): { spec+: { envoy+: { timeouts+: { streamIdleTimeout: streamIdleTimeout } } } },
      },
      '#withDefaultHTTPVersions':: d.fn(help='"DefaultHTTPVersions defines the default set of HTTPS\\nversions the proxy should accept. HTTP versions are\\nstrings of the form \\"HTTP/xx\\". Supported versions are\\n\\"HTTP/1.1\\" and \\"HTTP/2\\".\\nValues: `HTTP/1.1`, `HTTP/2` (default: both).\\nOther values will produce an error."', args=[d.arg(name='defaultHTTPVersions', type=d.T.array)]),
      withDefaultHTTPVersions(defaultHTTPVersions): { spec+: { envoy+: { defaultHTTPVersions: if std.isArray(v=defaultHTTPVersions) then defaultHTTPVersions else [defaultHTTPVersions] } } },
      '#withDefaultHTTPVersionsMixin':: d.fn(help='"DefaultHTTPVersions defines the default set of HTTPS\\nversions the proxy should accept. HTTP versions are\\nstrings of the form \\"HTTP/xx\\". Supported versions are\\n\\"HTTP/1.1\\" and \\"HTTP/2\\".\\nValues: `HTTP/1.1`, `HTTP/2` (default: both).\\nOther values will produce an error."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='defaultHTTPVersions', type=d.T.array)]),
      withDefaultHTTPVersionsMixin(defaultHTTPVersions): { spec+: { envoy+: { defaultHTTPVersions+: if std.isArray(v=defaultHTTPVersions) then defaultHTTPVersions else [defaultHTTPVersions] } } },
    },
    '#gateway':: d.obj(help='"Gateway contains parameters for the gateway-api Gateway that Contour\\nis configured to serve traffic."'),
    gateway: {
      '#gatewayRef':: d.obj(help='"GatewayRef defines the specific Gateway that this Contour\\ninstance corresponds to."'),
      gatewayRef: {
        '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { gateway+: { gatewayRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { gateway+: { gatewayRef+: { namespace: namespace } } } },
      },
    },
    '#globalExtAuth':: d.obj(help='"GlobalExternalAuthorization allows envoys external authorization filter\\nto be enabled for all virtual hosts."'),
    globalExtAuth: {
      '#authPolicy':: d.obj(help='"AuthPolicy sets a default authorization policy for client requests.\\nThis policy will be used unless overridden by individual routes."'),
      authPolicy: {
        '#withContext':: d.fn(help='"Context is a set of key/value pairs that are sent to the\\nauthentication server in the check request. If a context\\nis provided at an enclosing scope, the entries are merged\\nsuch that the inner scope overrides matching keys from the\\nouter scope."', args=[d.arg(name='context', type=d.T.object)]),
        withContext(context): { spec+: { globalExtAuth+: { authPolicy+: { context: context } } } },
        '#withContextMixin':: d.fn(help='"Context is a set of key/value pairs that are sent to the\\nauthentication server in the check request. If a context\\nis provided at an enclosing scope, the entries are merged\\nsuch that the inner scope overrides matching keys from the\\nouter scope."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='context', type=d.T.object)]),
        withContextMixin(context): { spec+: { globalExtAuth+: { authPolicy+: { context+: context } } } },
        '#withDisabled':: d.fn(help='"When true, this field disables client request authentication\\nfor the scope of the policy."', args=[d.arg(name='disabled', type=d.T.boolean)]),
        withDisabled(disabled): { spec+: { globalExtAuth+: { authPolicy+: { disabled: disabled } } } },
      },
      '#extensionRef':: d.obj(help='"ExtensionServiceRef specifies the extension resource that will authorize client requests."'),
      extensionRef: {
        '#withApiVersion':: d.fn(help='"API version of the referent.\\nIf this field is not specified, the default \\"projectcontour.io/v1alpha1\\" will be used"', args=[d.arg(name='apiVersion', type=d.T.string)]),
        withApiVersion(apiVersion): { spec+: { globalExtAuth+: { extensionRef+: { apiVersion: apiVersion } } } },
        '#withName':: d.fn(help='"Name of the referent.\\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { globalExtAuth+: { extensionRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent.\\nIf this field is not specifies, the namespace of the resource that targets the referent will be used.\\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { globalExtAuth+: { extensionRef+: { namespace: namespace } } } },
      },
      '#withFailOpen':: d.fn(help='"If FailOpen is true, the client request is forwarded to the upstream service\\neven if the authorization server fails to respond. This field should not be\\nset in most cases. It is intended for use only while migrating applications\\nfrom internal authorization to Contour external authorization."', args=[d.arg(name='failOpen', type=d.T.boolean)]),
      withFailOpen(failOpen): { spec+: { globalExtAuth+: { failOpen: failOpen } } },
      '#withRequestBody':: d.obj(help="\"WithRequestBody specifies configuration for sending the client request's body to authorization server.\""),
      withRequestBody: {
        '#withAllowPartialMessage':: d.fn(help='"If AllowPartialMessage is true, then Envoy will buffer the body until MaxRequestBytes are reached."', args=[d.arg(name='allowPartialMessage', type=d.T.boolean)]),
        withAllowPartialMessage(allowPartialMessage): { spec+: { globalExtAuth+: { withRequestBody+: { allowPartialMessage: allowPartialMessage } } } },
        '#withMaxRequestBytes':: d.fn(help='"MaxRequestBytes sets the maximum size of message body ExtAuthz filter will hold in-memory."', args=[d.arg(name='maxRequestBytes', type=d.T.integer)]),
        withMaxRequestBytes(maxRequestBytes): { spec+: { globalExtAuth+: { withRequestBody+: { maxRequestBytes: maxRequestBytes } } } },
        '#withPackAsBytes':: d.fn(help='"If PackAsBytes is true, the body sent to Authorization Server is in raw bytes."', args=[d.arg(name='packAsBytes', type=d.T.boolean)]),
        withPackAsBytes(packAsBytes): { spec+: { globalExtAuth+: { withRequestBody+: { packAsBytes: packAsBytes } } } },
      },
      '#withResponseTimeout':: d.fn(help='"ResponseTimeout configures maximum time to wait for a check response from the authorization server.\\nTimeout durations are expressed in the Go [Duration format](https://godoc.org/time#ParseDuration).\\nValid time units are \\"ns\\", \\"us\\" (or \\"µs\\"), \\"ms\\", \\"s\\", \\"m\\", \\"h\\".\\nThe string \\"infinity\\" is also a valid input and specifies no timeout."', args=[d.arg(name='responseTimeout', type=d.T.string)]),
      withResponseTimeout(responseTimeout): { spec+: { globalExtAuth+: { responseTimeout: responseTimeout } } },
    },
    '#health':: d.obj(help="\"Health defines the endpoints Contour uses to serve health checks.\\nContour's default is { address: \\\"0.0.0.0\\\", port: 8000 }.\""),
    health: {
      '#withAddress':: d.fn(help='"Defines the health address interface."', args=[d.arg(name='address', type=d.T.string)]),
      withAddress(address): { spec+: { health+: { address: address } } },
      '#withPort':: d.fn(help='"Defines the health port."', args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { health+: { port: port } } },
    },
    '#httpproxy':: d.obj(help='"HTTPProxy defines parameters on HTTPProxy."'),
    httpproxy: {
      '#fallbackCertificate':: d.obj(help='"FallbackCertificate defines the namespace/name of the Kubernetes secret to\\nuse as fallback when a non-SNI request is received."'),
      fallbackCertificate: {
        '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { httpproxy+: { fallbackCertificate+: { name: name } } } },
        '#withNamespace':: d.fn(help='', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { httpproxy+: { fallbackCertificate+: { namespace: namespace } } } },
      },
      '#withDisablePermitInsecure':: d.fn(help="\"DisablePermitInsecure disables the use of the\\npermitInsecure field in HTTPProxy.\\nContour's default is false.\"", args=[d.arg(name='disablePermitInsecure', type=d.T.boolean)]),
      withDisablePermitInsecure(disablePermitInsecure): { spec+: { httpproxy+: { disablePermitInsecure: disablePermitInsecure } } },
      '#withRootNamespaces':: d.fn(help='"Restrict Contour to searching these namespaces for root ingress routes."', args=[d.arg(name='rootNamespaces', type=d.T.array)]),
      withRootNamespaces(rootNamespaces): { spec+: { httpproxy+: { rootNamespaces: if std.isArray(v=rootNamespaces) then rootNamespaces else [rootNamespaces] } } },
      '#withRootNamespacesMixin':: d.fn(help='"Restrict Contour to searching these namespaces for root ingress routes."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='rootNamespaces', type=d.T.array)]),
      withRootNamespacesMixin(rootNamespaces): { spec+: { httpproxy+: { rootNamespaces+: if std.isArray(v=rootNamespaces) then rootNamespaces else [rootNamespaces] } } },
    },
    '#ingress':: d.obj(help='"Ingress contains parameters for ingress options."'),
    ingress: {
      '#withClassNames':: d.fn(help='"Ingress Class Names Contour should use."', args=[d.arg(name='classNames', type=d.T.array)]),
      withClassNames(classNames): { spec+: { ingress+: { classNames: if std.isArray(v=classNames) then classNames else [classNames] } } },
      '#withClassNamesMixin':: d.fn(help='"Ingress Class Names Contour should use."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='classNames', type=d.T.array)]),
      withClassNamesMixin(classNames): { spec+: { ingress+: { classNames+: if std.isArray(v=classNames) then classNames else [classNames] } } },
      '#withStatusAddress':: d.fn(help='"Address to set in Ingress object status."', args=[d.arg(name='statusAddress', type=d.T.string)]),
      withStatusAddress(statusAddress): { spec+: { ingress+: { statusAddress: statusAddress } } },
    },
    '#metrics':: d.obj(help="\"Metrics defines the endpoint Contour uses to serve metrics.\\nContour's default is { address: \\\"0.0.0.0\\\", port: 8000 }.\""),
    metrics: {
      '#tls':: d.obj(help='"TLS holds TLS file config details.\\nMetrics and health endpoints cannot have same port number when metrics is served over HTTPS."'),
      tls: {
        '#withCaFile':: d.fn(help='"CA filename."', args=[d.arg(name='caFile', type=d.T.string)]),
        withCaFile(caFile): { spec+: { metrics+: { tls+: { caFile: caFile } } } },
        '#withCertFile':: d.fn(help='"Client certificate filename."', args=[d.arg(name='certFile', type=d.T.string)]),
        withCertFile(certFile): { spec+: { metrics+: { tls+: { certFile: certFile } } } },
        '#withKeyFile':: d.fn(help='"Client key filename."', args=[d.arg(name='keyFile', type=d.T.string)]),
        withKeyFile(keyFile): { spec+: { metrics+: { tls+: { keyFile: keyFile } } } },
      },
      '#withAddress':: d.fn(help='"Defines the metrics address interface."', args=[d.arg(name='address', type=d.T.string)]),
      withAddress(address): { spec+: { metrics+: { address: address } } },
      '#withPort':: d.fn(help='"Defines the metrics port."', args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { metrics+: { port: port } } },
    },
    '#policy':: d.obj(help='"Policy specifies default policy applied if not overridden by the user"'),
    policy: {
      '#requestHeaders':: d.obj(help='"RequestHeadersPolicy defines the request headers set/removed on all routes"'),
      requestHeaders: {
        '#withRemove':: d.fn(help='', args=[d.arg(name='remove', type=d.T.array)]),
        withRemove(remove): { spec+: { policy+: { requestHeaders+: { remove: if std.isArray(v=remove) then remove else [remove] } } } },
        '#withRemoveMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remove', type=d.T.array)]),
        withRemoveMixin(remove): { spec+: { policy+: { requestHeaders+: { remove+: if std.isArray(v=remove) then remove else [remove] } } } },
        '#withSet':: d.fn(help='', args=[d.arg(name='set', type=d.T.object)]),
        withSet(set): { spec+: { policy+: { requestHeaders+: { set: set } } } },
        '#withSetMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='set', type=d.T.object)]),
        withSetMixin(set): { spec+: { policy+: { requestHeaders+: { set+: set } } } },
      },
      '#responseHeaders':: d.obj(help='"ResponseHeadersPolicy defines the response headers set/removed on all routes"'),
      responseHeaders: {
        '#withRemove':: d.fn(help='', args=[d.arg(name='remove', type=d.T.array)]),
        withRemove(remove): { spec+: { policy+: { responseHeaders+: { remove: if std.isArray(v=remove) then remove else [remove] } } } },
        '#withRemoveMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='remove', type=d.T.array)]),
        withRemoveMixin(remove): { spec+: { policy+: { responseHeaders+: { remove+: if std.isArray(v=remove) then remove else [remove] } } } },
        '#withSet':: d.fn(help='', args=[d.arg(name='set', type=d.T.object)]),
        withSet(set): { spec+: { policy+: { responseHeaders+: { set: set } } } },
        '#withSetMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='set', type=d.T.object)]),
        withSetMixin(set): { spec+: { policy+: { responseHeaders+: { set+: set } } } },
      },
      '#withApplyToIngress':: d.fn(help="\"ApplyToIngress determines if the Policies will apply to ingress objects\\nContour's default is false.\"", args=[d.arg(name='applyToIngress', type=d.T.boolean)]),
      withApplyToIngress(applyToIngress): { spec+: { policy+: { applyToIngress: applyToIngress } } },
    },
    '#rateLimitService':: d.obj(help='"RateLimitService optionally holds properties of the Rate Limit Service\\nto be used for global rate limiting."'),
    rateLimitService: {
      '#defaultGlobalRateLimitPolicy':: d.obj(help='"DefaultGlobalRateLimitPolicy allows setting a default global rate limit policy for every HTTPProxy.\\nHTTPProxy can overwrite this configuration."'),
      defaultGlobalRateLimitPolicy: {
        '#descriptors':: d.obj(help='"Descriptors defines the list of descriptors that will\\nbe generated and sent to the rate limit service. Each\\ndescriptor contains 1+ key-value pair entries."'),
        descriptors: {
          '#entries':: d.obj(help='"Entries is the list of key-value pair generators."'),
          entries: {
            '#genericKey':: d.obj(help='"GenericKey defines a descriptor entry with a static key and value."'),
            genericKey: {
              '#withKey':: d.fn(help='"Key defines the key of the descriptor entry. If not set, the\\nkey is set to \\"generic_key\\"."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { genericKey+: { key: key } },
              '#withValue':: d.fn(help='"Value defines the value of the descriptor entry."', args=[d.arg(name='value', type=d.T.string)]),
              withValue(value): { genericKey+: { value: value } },
            },
            '#requestHeader':: d.obj(help="\"RequestHeader defines a descriptor entry that's populated only if\\na given header is present on the request. The descriptor key is static,\\nand the descriptor value is equal to the value of the header.\""),
            requestHeader: {
              '#withDescriptorKey':: d.fn(help='"DescriptorKey defines the key to use on the descriptor entry."', args=[d.arg(name='descriptorKey', type=d.T.string)]),
              withDescriptorKey(descriptorKey): { requestHeader+: { descriptorKey: descriptorKey } },
              '#withHeaderName':: d.fn(help='"HeaderName defines the name of the header to look for on the request."', args=[d.arg(name='headerName', type=d.T.string)]),
              withHeaderName(headerName): { requestHeader+: { headerName: headerName } },
            },
            '#requestHeaderValueMatch':: d.obj(help="\"RequestHeaderValueMatch defines a descriptor entry that's populated\\nif the request's headers match a set of 1+ match criteria. The\\ndescriptor key is \\\"header_match\\\", and the descriptor value is static.\""),
            requestHeaderValueMatch: {
              '#headers':: d.obj(help='"Headers is a list of 1+ match criteria to apply against the request\\nto determine whether to populate the descriptor entry or not."'),
              headers: {
                '#withContains':: d.fn(help='"Contains specifies a substring that must be present in\\nthe header value."', args=[d.arg(name='contains', type=d.T.string)]),
                withContains(contains): { contains: contains },
                '#withExact':: d.fn(help='"Exact specifies a string that the header value must be equal to."', args=[d.arg(name='exact', type=d.T.string)]),
                withExact(exact): { exact: exact },
                '#withIgnoreCase':: d.fn(help='"IgnoreCase specifies that string matching should be case insensitive.\\nNote that this has no effect on the Regex parameter."', args=[d.arg(name='ignoreCase', type=d.T.boolean)]),
                withIgnoreCase(ignoreCase): { ignoreCase: ignoreCase },
                '#withName':: d.fn(help='"Name is the name of the header to match against. Name is required.\\nHeader names are case insensitive."', args=[d.arg(name='name', type=d.T.string)]),
                withName(name): { name: name },
                '#withNotcontains':: d.fn(help='"NotContains specifies a substring that must not be present\\nin the header value."', args=[d.arg(name='notcontains', type=d.T.string)]),
                withNotcontains(notcontains): { notcontains: notcontains },
                '#withNotexact':: d.fn(help='"NoExact specifies a string that the header value must not be\\nequal to. The condition is true if the header has any other value."', args=[d.arg(name='notexact', type=d.T.string)]),
                withNotexact(notexact): { notexact: notexact },
                '#withNotpresent':: d.fn(help='"NotPresent specifies that condition is true when the named header\\nis not present. Note that setting NotPresent to false does not\\nmake the condition true if the named header is present."', args=[d.arg(name='notpresent', type=d.T.boolean)]),
                withNotpresent(notpresent): { notpresent: notpresent },
                '#withPresent':: d.fn(help='"Present specifies that condition is true when the named header\\nis present, regardless of its value. Note that setting Present\\nto false does not make the condition true if the named header\\nis absent."', args=[d.arg(name='present', type=d.T.boolean)]),
                withPresent(present): { present: present },
                '#withRegex':: d.fn(help='"Regex specifies a regular expression pattern that must match the header\\nvalue."', args=[d.arg(name='regex', type=d.T.string)]),
                withRegex(regex): { regex: regex },
                '#withTreatMissingAsEmpty':: d.fn(help='"TreatMissingAsEmpty specifies if the header match rule specified header\\ndoes not exist, this header value will be treated as empty. Defaults to false.\\nUnlike the underlying Envoy implementation this is **only** supported for\\nnegative matches (e.g. NotContains, NotExact)."', args=[d.arg(name='treatMissingAsEmpty', type=d.T.boolean)]),
                withTreatMissingAsEmpty(treatMissingAsEmpty): { treatMissingAsEmpty: treatMissingAsEmpty },
              },
              '#withExpectMatch':: d.fn(help='"ExpectMatch defines whether the request must positively match the match\\ncriteria in order to generate a descriptor entry (i.e. true), or not\\nmatch the match criteria in order to generate a descriptor entry (i.e. false).\\nThe default is true."', args=[d.arg(name='expectMatch', type=d.T.boolean)]),
              withExpectMatch(expectMatch): { requestHeaderValueMatch+: { expectMatch: expectMatch } },
              '#withHeaders':: d.fn(help='"Headers is a list of 1+ match criteria to apply against the request\\nto determine whether to populate the descriptor entry or not."', args=[d.arg(name='headers', type=d.T.array)]),
              withHeaders(headers): { requestHeaderValueMatch+: { headers: if std.isArray(v=headers) then headers else [headers] } },
              '#withHeadersMixin':: d.fn(help='"Headers is a list of 1+ match criteria to apply against the request\\nto determine whether to populate the descriptor entry or not."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='headers', type=d.T.array)]),
              withHeadersMixin(headers): { requestHeaderValueMatch+: { headers+: if std.isArray(v=headers) then headers else [headers] } },
              '#withValue':: d.fn(help='"Value defines the value of the descriptor entry."', args=[d.arg(name='value', type=d.T.string)]),
              withValue(value): { requestHeaderValueMatch+: { value: value } },
            },
            '#withRemoteAddress':: d.fn(help="\"RemoteAddress defines a descriptor entry with a key of \\\"remote_address\\\"\\nand a value equal to the client's IP address (from x-forwarded-for).\"", args=[d.arg(name='remoteAddress', type=d.T.object)]),
            withRemoteAddress(remoteAddress): { remoteAddress: remoteAddress },
            '#withRemoteAddressMixin':: d.fn(help="\"RemoteAddress defines a descriptor entry with a key of \\\"remote_address\\\"\\nand a value equal to the client's IP address (from x-forwarded-for).\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='remoteAddress', type=d.T.object)]),
            withRemoteAddressMixin(remoteAddress): { remoteAddress+: remoteAddress },
          },
          '#withEntries':: d.fn(help='"Entries is the list of key-value pair generators."', args=[d.arg(name='entries', type=d.T.array)]),
          withEntries(entries): { entries: if std.isArray(v=entries) then entries else [entries] },
          '#withEntriesMixin':: d.fn(help='"Entries is the list of key-value pair generators."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='entries', type=d.T.array)]),
          withEntriesMixin(entries): { entries+: if std.isArray(v=entries) then entries else [entries] },
        },
        '#withDescriptors':: d.fn(help='"Descriptors defines the list of descriptors that will\\nbe generated and sent to the rate limit service. Each\\ndescriptor contains 1+ key-value pair entries."', args=[d.arg(name='descriptors', type=d.T.array)]),
        withDescriptors(descriptors): { spec+: { rateLimitService+: { defaultGlobalRateLimitPolicy+: { descriptors: if std.isArray(v=descriptors) then descriptors else [descriptors] } } } },
        '#withDescriptorsMixin':: d.fn(help='"Descriptors defines the list of descriptors that will\\nbe generated and sent to the rate limit service. Each\\ndescriptor contains 1+ key-value pair entries."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='descriptors', type=d.T.array)]),
        withDescriptorsMixin(descriptors): { spec+: { rateLimitService+: { defaultGlobalRateLimitPolicy+: { descriptors+: if std.isArray(v=descriptors) then descriptors else [descriptors] } } } },
        '#withDisabled':: d.fn(help='"Disabled configures the HTTPProxy to not use\\nthe default global rate limit policy defined by the Contour configuration."', args=[d.arg(name='disabled', type=d.T.boolean)]),
        withDisabled(disabled): { spec+: { rateLimitService+: { defaultGlobalRateLimitPolicy+: { disabled: disabled } } } },
      },
      '#extensionService':: d.obj(help='"ExtensionService identifies the extension service defining the RLS."'),
      extensionService: {
        '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { rateLimitService+: { extensionService+: { name: name } } } },
        '#withNamespace':: d.fn(help='', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { rateLimitService+: { extensionService+: { namespace: namespace } } } },
      },
      '#withDomain':: d.fn(help='"Domain is passed to the Rate Limit Service."', args=[d.arg(name='domain', type=d.T.string)]),
      withDomain(domain): { spec+: { rateLimitService+: { domain: domain } } },
      '#withEnableResourceExhaustedCode':: d.fn(help="\"EnableResourceExhaustedCode enables translating error code 429 to\\ngrpc code RESOURCE_EXHAUSTED. When disabled it's translated to UNAVAILABLE\"", args=[d.arg(name='enableResourceExhaustedCode', type=d.T.boolean)]),
      withEnableResourceExhaustedCode(enableResourceExhaustedCode): { spec+: { rateLimitService+: { enableResourceExhaustedCode: enableResourceExhaustedCode } } },
      '#withEnableXRateLimitHeaders':: d.fn(help='"EnableXRateLimitHeaders defines whether to include the X-RateLimit\\nheaders X-RateLimit-Limit, X-RateLimit-Remaining, and X-RateLimit-Reset\\n(as defined by the IETF Internet-Draft linked below), on responses\\nto clients when the Rate Limit Service is consulted for a request.\\nref. https://tools.ietf.org/id/draft-polli-ratelimit-headers-03.html"', args=[d.arg(name='enableXRateLimitHeaders', type=d.T.boolean)]),
      withEnableXRateLimitHeaders(enableXRateLimitHeaders): { spec+: { rateLimitService+: { enableXRateLimitHeaders: enableXRateLimitHeaders } } },
      '#withFailOpen':: d.fn(help='"FailOpen defines whether to allow requests to proceed when the\\nRate Limit Service fails to respond with a valid rate limit\\ndecision within the timeout defined on the extension service."', args=[d.arg(name='failOpen', type=d.T.boolean)]),
      withFailOpen(failOpen): { spec+: { rateLimitService+: { failOpen: failOpen } } },
    },
    '#tracing':: d.obj(help='"Tracing defines properties for exporting trace data to OpenTelemetry."'),
    tracing: {
      '#customTags':: d.obj(help='"CustomTags defines a list of custom tags with unique tag name."'),
      customTags: {
        '#withLiteral':: d.fn(help='"Literal is a static custom tag value.\\nPrecisely one of Literal, RequestHeaderName must be set."', args=[d.arg(name='literal', type=d.T.string)]),
        withLiteral(literal): { literal: literal },
        '#withRequestHeaderName':: d.fn(help='"RequestHeaderName indicates which request header\\nthe label value is obtained from.\\nPrecisely one of Literal, RequestHeaderName must be set."', args=[d.arg(name='requestHeaderName', type=d.T.string)]),
        withRequestHeaderName(requestHeaderName): { requestHeaderName: requestHeaderName },
        '#withTagName':: d.fn(help='"TagName is the unique name of the custom tag."', args=[d.arg(name='tagName', type=d.T.string)]),
        withTagName(tagName): { tagName: tagName },
      },
      '#extensionService':: d.obj(help='"ExtensionService identifies the extension service defining the otel-collector."'),
      extensionService: {
        '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { tracing+: { extensionService+: { name: name } } } },
        '#withNamespace':: d.fn(help='', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { tracing+: { extensionService+: { namespace: namespace } } } },
      },
      '#withCustomTags':: d.fn(help='"CustomTags defines a list of custom tags with unique tag name."', args=[d.arg(name='customTags', type=d.T.array)]),
      withCustomTags(customTags): { spec+: { tracing+: { customTags: if std.isArray(v=customTags) then customTags else [customTags] } } },
      '#withCustomTagsMixin':: d.fn(help='"CustomTags defines a list of custom tags with unique tag name."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='customTags', type=d.T.array)]),
      withCustomTagsMixin(customTags): { spec+: { tracing+: { customTags+: if std.isArray(v=customTags) then customTags else [customTags] } } },
      '#withIncludePodDetail':: d.fn(help='"IncludePodDetail defines a flag.\\nIf it is true, contour will add the pod name and namespace to the span of the trace.\\nthe default is true.\\nNote: The Envoy pods MUST have the HOSTNAME and CONTOUR_NAMESPACE environment variables set for this to work properly."', args=[d.arg(name='includePodDetail', type=d.T.boolean)]),
      withIncludePodDetail(includePodDetail): { spec+: { tracing+: { includePodDetail: includePodDetail } } },
      '#withMaxPathTagLength':: d.fn(help="\"MaxPathTagLength defines maximum length of the request path\\nto extract and include in the HttpUrl tag.\\ncontour's default is 256.\"", args=[d.arg(name='maxPathTagLength', type=d.T.integer)]),
      withMaxPathTagLength(maxPathTagLength): { spec+: { tracing+: { maxPathTagLength: maxPathTagLength } } },
      '#withOverallSampling':: d.fn(help="\"OverallSampling defines the sampling rate of trace data.\\ncontour's default is 100.\"", args=[d.arg(name='overallSampling', type=d.T.string)]),
      withOverallSampling(overallSampling): { spec+: { tracing+: { overallSampling: overallSampling } } },
      '#withServiceName':: d.fn(help="\"ServiceName defines the name for the service.\\ncontour's default is contour.\"", args=[d.arg(name='serviceName', type=d.T.string)]),
      withServiceName(serviceName): { spec+: { tracing+: { serviceName: serviceName } } },
    },
    '#withEnableExternalNameService':: d.fn(help="\"EnableExternalNameService allows processing of ExternalNameServices\\nContour's default is false for security reasons.\"", args=[d.arg(name='enableExternalNameService', type=d.T.boolean)]),
    withEnableExternalNameService(enableExternalNameService): { spec+: { enableExternalNameService: enableExternalNameService } },
    '#withFeatureFlags':: d.fn(help='"FeatureFlags defines toggle to enable new contour features.\\nAvailable toggles are:\\nuseEndpointSlices - Configures contour to fetch endpoint data\\nfrom k8s endpoint slices. defaults to true,\\nIf false then reads endpoint data from the k8s endpoints."', args=[d.arg(name='featureFlags', type=d.T.array)]),
    withFeatureFlags(featureFlags): { spec+: { featureFlags: if std.isArray(v=featureFlags) then featureFlags else [featureFlags] } },
    '#withFeatureFlagsMixin':: d.fn(help='"FeatureFlags defines toggle to enable new contour features.\\nAvailable toggles are:\\nuseEndpointSlices - Configures contour to fetch endpoint data\\nfrom k8s endpoint slices. defaults to true,\\nIf false then reads endpoint data from the k8s endpoints."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='featureFlags', type=d.T.array)]),
    withFeatureFlagsMixin(featureFlags): { spec+: { featureFlags+: if std.isArray(v=featureFlags) then featureFlags else [featureFlags] } },
    '#xdsServer':: d.obj(help='"XDSServer contains parameters for the xDS server."'),
    xdsServer: {
      '#tls':: d.obj(help="\"TLS holds TLS file config details.\\nContour's default is { caFile: \\\"/certs/ca.crt\\\", certFile: \\\"/certs/tls.cert\\\", keyFile: \\\"/certs/tls.key\\\", insecure: false }.\""),
      tls: {
        '#withCaFile':: d.fn(help='"CA filename."', args=[d.arg(name='caFile', type=d.T.string)]),
        withCaFile(caFile): { spec+: { xdsServer+: { tls+: { caFile: caFile } } } },
        '#withCertFile':: d.fn(help='"Client certificate filename."', args=[d.arg(name='certFile', type=d.T.string)]),
        withCertFile(certFile): { spec+: { xdsServer+: { tls+: { certFile: certFile } } } },
        '#withInsecure':: d.fn(help='"Allow serving the xDS gRPC API without TLS."', args=[d.arg(name='insecure', type=d.T.boolean)]),
        withInsecure(insecure): { spec+: { xdsServer+: { tls+: { insecure: insecure } } } },
        '#withKeyFile':: d.fn(help='"Client key filename."', args=[d.arg(name='keyFile', type=d.T.string)]),
        withKeyFile(keyFile): { spec+: { xdsServer+: { tls+: { keyFile: keyFile } } } },
      },
      '#withAddress':: d.fn(help="\"Defines the xDS gRPC API address which Contour will serve.\\nContour's default is \\\"0.0.0.0\\\".\"", args=[d.arg(name='address', type=d.T.string)]),
      withAddress(address): { spec+: { xdsServer+: { address: address } } },
      '#withPort':: d.fn(help="\"Defines the xDS gRPC API port which Contour will serve.\\nContour's default is 8001.\"", args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { xdsServer+: { port: port } } },
      '#withType':: d.fn(help='"Defines the XDSServer to use for `contour serve`.\\nValues: `envoy` (default), `contour (deprecated)`.\\nOther values will produce an error.\\nDeprecated: this field will be removed in a future release when\\nthe `contour` xDS server implementation is removed."', args=[d.arg(name='type', type=d.T.string)]),
      withType(type): { spec+: { xdsServer+: { type: type } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
